services:

  otel-collector:
    image: otel/opentelemetry-collector
    volumes:
      - ./otelcol/config.yaml:/etc/otelcol-contrib/config.yaml:ro
    ports:
      - 1888:1888 # pprof extension
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension


# volumes:

# networks: