// Code generated by ogen, DO NOT EDIT.
package api

type AdminUsersUserIdRevokeChainPostRes interface {
	adminUsersUserIdRevokeChainPostRes()
}

type AuthVerifyGetRes interface {
	authVerifyGetRes()
}

type InvitesPostRes interface {
	invitesPostRes()
}

type LoginBeginPostRes interface {
	loginBeginPostRes()
}

type LoginPostRes interface {
	loginPostRes()
}

type RegistrationBeginPostRes interface {
	registrationBeginPostRes()
}

type RegistrationCompletePostRes interface {
	registrationCompletePostRes()
}

type SessionsSessionIdDeleteRes interface {
	sessionsSessionIdDeleteRes()
}

type TokenRefreshPostRes interface {
	tokenRefreshPostRes()
}
