// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AdminUsersUserIdRevokeChainPost implements POST /admin/users/{userId}/revoke-chain operation.
//
// Каскадный отзыв сессий по цепочке приглашений.
//
// POST /admin/users/{userId}/revoke-chain
func (UnimplementedHandler) AdminUsersUserIdRevokeChainPost(ctx context.Context, params AdminUsersUserIdRevokeChainPostParams) (r AdminUsersUserIdRevokeChainPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AuthVerifyGet implements AuthVerifyGet operation.
//
// Проверяет Bearer access token для Traefik ForwardAuth.
//
// GET /auth/verify
func (UnimplementedHandler) AuthVerifyGet(ctx context.Context) (r AuthVerifyGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// InvitesPost implements POST /invites operation.
//
// Создаёт инвайт от лица текущего авторизованного
// пользователя. UserID берётся из Bearer токена (PASETO) в middleware.
//
// POST /invites
func (UnimplementedHandler) InvitesPost(ctx context.Context) (r InvitesPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// LoginBeginPost implements POST /login/begin operation.
//
// Начать вход.
//
// POST /login/begin
func (UnimplementedHandler) LoginBeginPost(ctx context.Context) (r LoginBeginPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// LoginPost implements POST /login operation.
//
// Завершить вход.
//
// POST /login
func (UnimplementedHandler) LoginPost(ctx context.Context, req *LoginPostReq) (r LoginPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RegistrationBeginPost implements POST /registration/begin operation.
//
// Начать регистрацию по инвайт-коду.
//
// POST /registration/begin
func (UnimplementedHandler) RegistrationBeginPost(ctx context.Context, req *RegistrationBeginPostReq) (r RegistrationBeginPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RegistrationCompletePost implements POST /registration/complete operation.
//
// Завершает регистрацию. IP-адрес извлекается из
// HTTP-запроса на уровне хендлера.
//
// POST /registration/complete
func (UnimplementedHandler) RegistrationCompletePost(ctx context.Context, req *RegistrationCompletePostReq) (r RegistrationCompletePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SessionsSessionIdDelete implements DELETE /sessions/{sessionId} operation.
//
// Отзыв конкретной сессии по её ID.
//
// DELETE /sessions/{sessionId}
func (UnimplementedHandler) SessionsSessionIdDelete(ctx context.Context, params SessionsSessionIdDeleteParams) (r SessionsSessionIdDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TokenRefreshPost implements POST /token/refresh operation.
//
// Обновить access-токен.
//
// POST /token/refresh
func (UnimplementedHandler) TokenRefreshPost(ctx context.Context, req *TokenRefreshPostReq) (r TokenRefreshPostRes, _ error) {
	return r, ht.ErrNotImplemented
}
