// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/validate"
)

func (s *AdminUsersUserIdRevokeChainPostBadRequest) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AdminUsersUserIdRevokeChainPostForbidden) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AdminUsersUserIdRevokeChainPostInternalServerError) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AdminUsersUserIdRevokeChainPostNotFound) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AdminUsersUserIdRevokeChainPostUnauthorized) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AuthVerifyGetInternalServerError) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *AuthVerifyGetUnauthorized) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ErrorResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Error.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "error",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *ErrorResponseError) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Code.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "code",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s ErrorResponseErrorCode) Validate() error {
	switch s {
	case "VALIDATION_ERROR":
		return nil
	case "UNAUTHORIZED":
		return nil
	case "FORBIDDEN":
		return nil
	case "NOT_FOUND":
		return nil
	case "INVITE_NOT_FOUND":
		return nil
	case "INVITE_EXPIRED":
		return nil
	case "INVITE_ALREADY_USED":
		return nil
	case "INVITE_LIMIT_EXCEEDED":
		return nil
	case "WRAPPED_KEYS_REQUIRED":
		return nil
	case "CHALLENGE_EXPIRED":
		return nil
	case "CREDENTIAL_NOT_FOUND":
		return nil
	case "CREDENTIAL_REVOKED":
		return nil
	case "CREDENTIAL_CLONE_SUSPECTED":
		return nil
	case "REFRESH_TOKEN_NOT_FOUND":
		return nil
	case "REFRESH_TOKEN_INVALID":
		return nil
	case "REFRESH_TOKEN_REUSE_DETECTED":
		return nil
	case "SESSION_NOT_FOUND":
		return nil
	case "SESSION_FORBIDDEN":
		return nil
	case "INTERNAL_ERROR":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *InvitesPostBadRequest) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *InvitesPostConflict) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *InvitesPostInternalServerError) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *InvitesPostUnauthorized) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *LoginPostBadRequest) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *LoginPostInternalServerError) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *LoginPostOK) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.WrappedKeys == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.WrappedKeys {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "wrappedKeys",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *LoginPostUnauthorized) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *RegistrationBeginPostBadRequest) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *RegistrationBeginPostConflict) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *RegistrationBeginPostInternalServerError) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *RegistrationBeginPostNotFound) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *RegistrationCompletePostBadRequest) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *RegistrationCompletePostConflict) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *RegistrationCompletePostInternalServerError) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *RegistrationCompletePostNotFound) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *RegistrationCompletePostReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.WrappedKeys == nil {
			return errors.New("nil is invalid value")
		}
		if err := (validate.Array{
			MinLength:    1,
			MinLengthSet: true,
			MaxLength:    0,
			MaxLengthSet: false,
		}).ValidateLength(len(s.WrappedKeys)); err != nil {
			return errors.Wrap(err, "array")
		}
		var failures []validate.FieldError
		for i, elem := range s.WrappedKeys {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "wrappedKeys",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *RegistrationCompletePostUnauthorized) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *SessionsSessionIdDeleteBadRequest) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *SessionsSessionIdDeleteForbidden) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *SessionsSessionIdDeleteInternalServerError) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *SessionsSessionIdDeleteNotFound) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *SessionsSessionIdDeleteUnauthorized) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TokenRefreshPostBadRequest) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TokenRefreshPostInternalServerError) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TokenRefreshPostUnauthorized) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *WrappedKeyInput) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Scope.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "scope",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *WrappedKeyOutput) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Scope.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "scope",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s WrappedKeyScope) Validate() error {
	switch s {
	case "main":
		return nil
	case "decoy":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}
