// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/google/uuid"
)

type AdminUsersUserIdRevokeChainPostBadRequest ErrorResponse

func (*AdminUsersUserIdRevokeChainPostBadRequest) adminUsersUserIdRevokeChainPostRes() {}

type AdminUsersUserIdRevokeChainPostForbidden ErrorResponse

func (*AdminUsersUserIdRevokeChainPostForbidden) adminUsersUserIdRevokeChainPostRes() {}

type AdminUsersUserIdRevokeChainPostInternalServerError ErrorResponse

func (*AdminUsersUserIdRevokeChainPostInternalServerError) adminUsersUserIdRevokeChainPostRes() {}

// AdminUsersUserIdRevokeChainPostNoContent is response for AdminUsersUserIdRevokeChainPost operation.
type AdminUsersUserIdRevokeChainPostNoContent struct{}

func (*AdminUsersUserIdRevokeChainPostNoContent) adminUsersUserIdRevokeChainPostRes() {}

type AdminUsersUserIdRevokeChainPostNotFound ErrorResponse

func (*AdminUsersUserIdRevokeChainPostNotFound) adminUsersUserIdRevokeChainPostRes() {}

type AdminUsersUserIdRevokeChainPostUnauthorized ErrorResponse

func (*AdminUsersUserIdRevokeChainPostUnauthorized) adminUsersUserIdRevokeChainPostRes() {}

type AuthVerifyGetInternalServerError ErrorResponse

func (*AuthVerifyGetInternalServerError) authVerifyGetRes() {}

// AuthVerifyGetNoContent is response for AuthVerifyGet operation.
type AuthVerifyGetNoContent struct {
	XAuthUser uuid.UUID
}

// GetXAuthUser returns the value of XAuthUser.
func (s *AuthVerifyGetNoContent) GetXAuthUser() uuid.UUID {
	return s.XAuthUser
}

// SetXAuthUser sets the value of XAuthUser.
func (s *AuthVerifyGetNoContent) SetXAuthUser(val uuid.UUID) {
	s.XAuthUser = val
}

func (*AuthVerifyGetNoContent) authVerifyGetRes() {}

type AuthVerifyGetUnauthorized ErrorResponse

func (*AuthVerifyGetUnauthorized) authVerifyGetRes() {}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Error ErrorResponseError `json:"error"`
}

// GetError returns the value of Error.
func (s *ErrorResponse) GetError() ErrorResponseError {
	return s.Error
}

// SetError sets the value of Error.
func (s *ErrorResponse) SetError(val ErrorResponseError) {
	s.Error = val
}

func (*ErrorResponse) loginBeginPostRes() {}

type ErrorResponseError struct {
	Code    ErrorResponseErrorCode `json:"code"`
	Message string                 `json:"message"`
}

// GetCode returns the value of Code.
func (s *ErrorResponseError) GetCode() ErrorResponseErrorCode {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ErrorResponseError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ErrorResponseError) SetCode(val ErrorResponseErrorCode) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ErrorResponseError) SetMessage(val string) {
	s.Message = val
}

type ErrorResponseErrorCode string

const (
	ErrorResponseErrorCodeVALIDATIONERROR           ErrorResponseErrorCode = "VALIDATION_ERROR"
	ErrorResponseErrorCodeUNAUTHORIZED              ErrorResponseErrorCode = "UNAUTHORIZED"
	ErrorResponseErrorCodeFORBIDDEN                 ErrorResponseErrorCode = "FORBIDDEN"
	ErrorResponseErrorCodeNOTFOUND                  ErrorResponseErrorCode = "NOT_FOUND"
	ErrorResponseErrorCodeINVITENOTFOUND            ErrorResponseErrorCode = "INVITE_NOT_FOUND"
	ErrorResponseErrorCodeINVITEEXPIRED             ErrorResponseErrorCode = "INVITE_EXPIRED"
	ErrorResponseErrorCodeINVITEALREADYUSED         ErrorResponseErrorCode = "INVITE_ALREADY_USED"
	ErrorResponseErrorCodeINVITELIMITEXCEEDED       ErrorResponseErrorCode = "INVITE_LIMIT_EXCEEDED"
	ErrorResponseErrorCodeWRAPPEDKEYSREQUIRED       ErrorResponseErrorCode = "WRAPPED_KEYS_REQUIRED"
	ErrorResponseErrorCodeCHALLENGEEXPIRED          ErrorResponseErrorCode = "CHALLENGE_EXPIRED"
	ErrorResponseErrorCodeCREDENTIALNOTFOUND        ErrorResponseErrorCode = "CREDENTIAL_NOT_FOUND"
	ErrorResponseErrorCodeCREDENTIALREVOKED         ErrorResponseErrorCode = "CREDENTIAL_REVOKED"
	ErrorResponseErrorCodeCREDENTIALCLONESUSPECTED  ErrorResponseErrorCode = "CREDENTIAL_CLONE_SUSPECTED"
	ErrorResponseErrorCodeREFRESHTOKENNOTFOUND      ErrorResponseErrorCode = "REFRESH_TOKEN_NOT_FOUND"
	ErrorResponseErrorCodeREFRESHTOKENINVALID       ErrorResponseErrorCode = "REFRESH_TOKEN_INVALID"
	ErrorResponseErrorCodeREFRESHTOKENREUSEDETECTED ErrorResponseErrorCode = "REFRESH_TOKEN_REUSE_DETECTED"
	ErrorResponseErrorCodeSESSIONNOTFOUND           ErrorResponseErrorCode = "SESSION_NOT_FOUND"
	ErrorResponseErrorCodeSESSIONFORBIDDEN          ErrorResponseErrorCode = "SESSION_FORBIDDEN"
	ErrorResponseErrorCodeINTERNALERROR             ErrorResponseErrorCode = "INTERNAL_ERROR"
)

// AllValues returns all ErrorResponseErrorCode values.
func (ErrorResponseErrorCode) AllValues() []ErrorResponseErrorCode {
	return []ErrorResponseErrorCode{
		ErrorResponseErrorCodeVALIDATIONERROR,
		ErrorResponseErrorCodeUNAUTHORIZED,
		ErrorResponseErrorCodeFORBIDDEN,
		ErrorResponseErrorCodeNOTFOUND,
		ErrorResponseErrorCodeINVITENOTFOUND,
		ErrorResponseErrorCodeINVITEEXPIRED,
		ErrorResponseErrorCodeINVITEALREADYUSED,
		ErrorResponseErrorCodeINVITELIMITEXCEEDED,
		ErrorResponseErrorCodeWRAPPEDKEYSREQUIRED,
		ErrorResponseErrorCodeCHALLENGEEXPIRED,
		ErrorResponseErrorCodeCREDENTIALNOTFOUND,
		ErrorResponseErrorCodeCREDENTIALREVOKED,
		ErrorResponseErrorCodeCREDENTIALCLONESUSPECTED,
		ErrorResponseErrorCodeREFRESHTOKENNOTFOUND,
		ErrorResponseErrorCodeREFRESHTOKENINVALID,
		ErrorResponseErrorCodeREFRESHTOKENREUSEDETECTED,
		ErrorResponseErrorCodeSESSIONNOTFOUND,
		ErrorResponseErrorCodeSESSIONFORBIDDEN,
		ErrorResponseErrorCodeINTERNALERROR,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ErrorResponseErrorCode) MarshalText() ([]byte, error) {
	switch s {
	case ErrorResponseErrorCodeVALIDATIONERROR:
		return []byte(s), nil
	case ErrorResponseErrorCodeUNAUTHORIZED:
		return []byte(s), nil
	case ErrorResponseErrorCodeFORBIDDEN:
		return []byte(s), nil
	case ErrorResponseErrorCodeNOTFOUND:
		return []byte(s), nil
	case ErrorResponseErrorCodeINVITENOTFOUND:
		return []byte(s), nil
	case ErrorResponseErrorCodeINVITEEXPIRED:
		return []byte(s), nil
	case ErrorResponseErrorCodeINVITEALREADYUSED:
		return []byte(s), nil
	case ErrorResponseErrorCodeINVITELIMITEXCEEDED:
		return []byte(s), nil
	case ErrorResponseErrorCodeWRAPPEDKEYSREQUIRED:
		return []byte(s), nil
	case ErrorResponseErrorCodeCHALLENGEEXPIRED:
		return []byte(s), nil
	case ErrorResponseErrorCodeCREDENTIALNOTFOUND:
		return []byte(s), nil
	case ErrorResponseErrorCodeCREDENTIALREVOKED:
		return []byte(s), nil
	case ErrorResponseErrorCodeCREDENTIALCLONESUSPECTED:
		return []byte(s), nil
	case ErrorResponseErrorCodeREFRESHTOKENNOTFOUND:
		return []byte(s), nil
	case ErrorResponseErrorCodeREFRESHTOKENINVALID:
		return []byte(s), nil
	case ErrorResponseErrorCodeREFRESHTOKENREUSEDETECTED:
		return []byte(s), nil
	case ErrorResponseErrorCodeSESSIONNOTFOUND:
		return []byte(s), nil
	case ErrorResponseErrorCodeSESSIONFORBIDDEN:
		return []byte(s), nil
	case ErrorResponseErrorCodeINTERNALERROR:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ErrorResponseErrorCode) UnmarshalText(data []byte) error {
	switch ErrorResponseErrorCode(data) {
	case ErrorResponseErrorCodeVALIDATIONERROR:
		*s = ErrorResponseErrorCodeVALIDATIONERROR
		return nil
	case ErrorResponseErrorCodeUNAUTHORIZED:
		*s = ErrorResponseErrorCodeUNAUTHORIZED
		return nil
	case ErrorResponseErrorCodeFORBIDDEN:
		*s = ErrorResponseErrorCodeFORBIDDEN
		return nil
	case ErrorResponseErrorCodeNOTFOUND:
		*s = ErrorResponseErrorCodeNOTFOUND
		return nil
	case ErrorResponseErrorCodeINVITENOTFOUND:
		*s = ErrorResponseErrorCodeINVITENOTFOUND
		return nil
	case ErrorResponseErrorCodeINVITEEXPIRED:
		*s = ErrorResponseErrorCodeINVITEEXPIRED
		return nil
	case ErrorResponseErrorCodeINVITEALREADYUSED:
		*s = ErrorResponseErrorCodeINVITEALREADYUSED
		return nil
	case ErrorResponseErrorCodeINVITELIMITEXCEEDED:
		*s = ErrorResponseErrorCodeINVITELIMITEXCEEDED
		return nil
	case ErrorResponseErrorCodeWRAPPEDKEYSREQUIRED:
		*s = ErrorResponseErrorCodeWRAPPEDKEYSREQUIRED
		return nil
	case ErrorResponseErrorCodeCHALLENGEEXPIRED:
		*s = ErrorResponseErrorCodeCHALLENGEEXPIRED
		return nil
	case ErrorResponseErrorCodeCREDENTIALNOTFOUND:
		*s = ErrorResponseErrorCodeCREDENTIALNOTFOUND
		return nil
	case ErrorResponseErrorCodeCREDENTIALREVOKED:
		*s = ErrorResponseErrorCodeCREDENTIALREVOKED
		return nil
	case ErrorResponseErrorCodeCREDENTIALCLONESUSPECTED:
		*s = ErrorResponseErrorCodeCREDENTIALCLONESUSPECTED
		return nil
	case ErrorResponseErrorCodeREFRESHTOKENNOTFOUND:
		*s = ErrorResponseErrorCodeREFRESHTOKENNOTFOUND
		return nil
	case ErrorResponseErrorCodeREFRESHTOKENINVALID:
		*s = ErrorResponseErrorCodeREFRESHTOKENINVALID
		return nil
	case ErrorResponseErrorCodeREFRESHTOKENREUSEDETECTED:
		*s = ErrorResponseErrorCodeREFRESHTOKENREUSEDETECTED
		return nil
	case ErrorResponseErrorCodeSESSIONNOTFOUND:
		*s = ErrorResponseErrorCodeSESSIONNOTFOUND
		return nil
	case ErrorResponseErrorCodeSESSIONFORBIDDEN:
		*s = ErrorResponseErrorCodeSESSIONFORBIDDEN
		return nil
	case ErrorResponseErrorCodeINTERNALERROR:
		*s = ErrorResponseErrorCodeINTERNALERROR
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Invite
type Invite struct {
	// Сырой инвайт-код (возвращается один раз).
	Code      string    `json:"code"`
	ExpiresAt time.Time `json:"expiresAt"`
}

// GetCode returns the value of Code.
func (s *Invite) GetCode() string {
	return s.Code
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *Invite) GetExpiresAt() time.Time {
	return s.ExpiresAt
}

// SetCode sets the value of Code.
func (s *Invite) SetCode(val string) {
	s.Code = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *Invite) SetExpiresAt(val time.Time) {
	s.ExpiresAt = val
}

func (*Invite) invitesPostRes() {}

type InvitesPostBadRequest ErrorResponse

func (*InvitesPostBadRequest) invitesPostRes() {}

type InvitesPostConflict ErrorResponse

func (*InvitesPostConflict) invitesPostRes() {}

type InvitesPostInternalServerError ErrorResponse

func (*InvitesPostInternalServerError) invitesPostRes() {}

type InvitesPostUnauthorized ErrorResponse

func (*InvitesPostUnauthorized) invitesPostRes() {}

type LoginBeginPostOK struct {
	ChallengeToken string                 `json:"challengeToken"`
	RequestOptions WebAuthnRequestOptions `json:"requestOptions"`
}

// GetChallengeToken returns the value of ChallengeToken.
func (s *LoginBeginPostOK) GetChallengeToken() string {
	return s.ChallengeToken
}

// GetRequestOptions returns the value of RequestOptions.
func (s *LoginBeginPostOK) GetRequestOptions() WebAuthnRequestOptions {
	return s.RequestOptions
}

// SetChallengeToken sets the value of ChallengeToken.
func (s *LoginBeginPostOK) SetChallengeToken(val string) {
	s.ChallengeToken = val
}

// SetRequestOptions sets the value of RequestOptions.
func (s *LoginBeginPostOK) SetRequestOptions(val WebAuthnRequestOptions) {
	s.RequestOptions = val
}

func (*LoginBeginPostOK) loginBeginPostRes() {}

type LoginPostBadRequest ErrorResponse

func (*LoginPostBadRequest) loginPostRes() {}

type LoginPostInternalServerError ErrorResponse

func (*LoginPostInternalServerError) loginPostRes() {}

type LoginPostOK struct {
	TokenPair   TokenPair          `json:"tokenPair"`
	WrappedKeys []WrappedKeyOutput `json:"wrappedKeys"`
}

// GetTokenPair returns the value of TokenPair.
func (s *LoginPostOK) GetTokenPair() TokenPair {
	return s.TokenPair
}

// GetWrappedKeys returns the value of WrappedKeys.
func (s *LoginPostOK) GetWrappedKeys() []WrappedKeyOutput {
	return s.WrappedKeys
}

// SetTokenPair sets the value of TokenPair.
func (s *LoginPostOK) SetTokenPair(val TokenPair) {
	s.TokenPair = val
}

// SetWrappedKeys sets the value of WrappedKeys.
func (s *LoginPostOK) SetWrappedKeys(val []WrappedKeyOutput) {
	s.WrappedKeys = val
}

func (*LoginPostOK) loginPostRes() {}

type LoginPostReq struct {
	ChallengeToken         string                         `json:"challengeToken"`
	AuthenticationResponse WebAuthnAuthenticationResponse `json:"authenticationResponse"`
	DeviceInfo             OptString                      `json:"deviceInfo"`
}

// GetChallengeToken returns the value of ChallengeToken.
func (s *LoginPostReq) GetChallengeToken() string {
	return s.ChallengeToken
}

// GetAuthenticationResponse returns the value of AuthenticationResponse.
func (s *LoginPostReq) GetAuthenticationResponse() WebAuthnAuthenticationResponse {
	return s.AuthenticationResponse
}

// GetDeviceInfo returns the value of DeviceInfo.
func (s *LoginPostReq) GetDeviceInfo() OptString {
	return s.DeviceInfo
}

// SetChallengeToken sets the value of ChallengeToken.
func (s *LoginPostReq) SetChallengeToken(val string) {
	s.ChallengeToken = val
}

// SetAuthenticationResponse sets the value of AuthenticationResponse.
func (s *LoginPostReq) SetAuthenticationResponse(val WebAuthnAuthenticationResponse) {
	s.AuthenticationResponse = val
}

// SetDeviceInfo sets the value of DeviceInfo.
func (s *LoginPostReq) SetDeviceInfo(val OptString) {
	s.DeviceInfo = val
}

type LoginPostUnauthorized ErrorResponse

func (*LoginPostUnauthorized) loginPostRes() {}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type RegistrationBeginPostBadRequest ErrorResponse

func (*RegistrationBeginPostBadRequest) registrationBeginPostRes() {}

type RegistrationBeginPostConflict ErrorResponse

func (*RegistrationBeginPostConflict) registrationBeginPostRes() {}

type RegistrationBeginPostInternalServerError ErrorResponse

func (*RegistrationBeginPostInternalServerError) registrationBeginPostRes() {}

type RegistrationBeginPostNotFound ErrorResponse

func (*RegistrationBeginPostNotFound) registrationBeginPostRes() {}

type RegistrationBeginPostOK struct {
	ChallengeToken  string                  `json:"challengeToken"`
	CreationOptions WebAuthnCreationOptions `json:"creationOptions"`
}

// GetChallengeToken returns the value of ChallengeToken.
func (s *RegistrationBeginPostOK) GetChallengeToken() string {
	return s.ChallengeToken
}

// GetCreationOptions returns the value of CreationOptions.
func (s *RegistrationBeginPostOK) GetCreationOptions() WebAuthnCreationOptions {
	return s.CreationOptions
}

// SetChallengeToken sets the value of ChallengeToken.
func (s *RegistrationBeginPostOK) SetChallengeToken(val string) {
	s.ChallengeToken = val
}

// SetCreationOptions sets the value of CreationOptions.
func (s *RegistrationBeginPostOK) SetCreationOptions(val WebAuthnCreationOptions) {
	s.CreationOptions = val
}

func (*RegistrationBeginPostOK) registrationBeginPostRes() {}

type RegistrationBeginPostReq struct {
	InviteCode string `json:"inviteCode"`
}

// GetInviteCode returns the value of InviteCode.
func (s *RegistrationBeginPostReq) GetInviteCode() string {
	return s.InviteCode
}

// SetInviteCode sets the value of InviteCode.
func (s *RegistrationBeginPostReq) SetInviteCode(val string) {
	s.InviteCode = val
}

type RegistrationCompletePostBadRequest ErrorResponse

func (*RegistrationCompletePostBadRequest) registrationCompletePostRes() {}

type RegistrationCompletePostConflict ErrorResponse

func (*RegistrationCompletePostConflict) registrationCompletePostRes() {}

type RegistrationCompletePostInternalServerError ErrorResponse

func (*RegistrationCompletePostInternalServerError) registrationCompletePostRes() {}

type RegistrationCompletePostNotFound ErrorResponse

func (*RegistrationCompletePostNotFound) registrationCompletePostRes() {}

type RegistrationCompletePostReq struct {
	ChallengeToken       string                       `json:"challengeToken"`
	RegistrationResponse WebAuthnRegistrationResponse `json:"registrationResponse"`
	WrappedKeys          []WrappedKeyInput            `json:"wrappedKeys"`
	DeviceInfo           OptString                    `json:"deviceInfo"`
}

// GetChallengeToken returns the value of ChallengeToken.
func (s *RegistrationCompletePostReq) GetChallengeToken() string {
	return s.ChallengeToken
}

// GetRegistrationResponse returns the value of RegistrationResponse.
func (s *RegistrationCompletePostReq) GetRegistrationResponse() WebAuthnRegistrationResponse {
	return s.RegistrationResponse
}

// GetWrappedKeys returns the value of WrappedKeys.
func (s *RegistrationCompletePostReq) GetWrappedKeys() []WrappedKeyInput {
	return s.WrappedKeys
}

// GetDeviceInfo returns the value of DeviceInfo.
func (s *RegistrationCompletePostReq) GetDeviceInfo() OptString {
	return s.DeviceInfo
}

// SetChallengeToken sets the value of ChallengeToken.
func (s *RegistrationCompletePostReq) SetChallengeToken(val string) {
	s.ChallengeToken = val
}

// SetRegistrationResponse sets the value of RegistrationResponse.
func (s *RegistrationCompletePostReq) SetRegistrationResponse(val WebAuthnRegistrationResponse) {
	s.RegistrationResponse = val
}

// SetWrappedKeys sets the value of WrappedKeys.
func (s *RegistrationCompletePostReq) SetWrappedKeys(val []WrappedKeyInput) {
	s.WrappedKeys = val
}

// SetDeviceInfo sets the value of DeviceInfo.
func (s *RegistrationCompletePostReq) SetDeviceInfo(val OptString) {
	s.DeviceInfo = val
}

type RegistrationCompletePostUnauthorized ErrorResponse

func (*RegistrationCompletePostUnauthorized) registrationCompletePostRes() {}

type SessionsSessionIdDeleteBadRequest ErrorResponse

func (*SessionsSessionIdDeleteBadRequest) sessionsSessionIdDeleteRes() {}

type SessionsSessionIdDeleteForbidden ErrorResponse

func (*SessionsSessionIdDeleteForbidden) sessionsSessionIdDeleteRes() {}

type SessionsSessionIdDeleteInternalServerError ErrorResponse

func (*SessionsSessionIdDeleteInternalServerError) sessionsSessionIdDeleteRes() {}

// SessionsSessionIdDeleteNoContent is response for SessionsSessionIdDelete operation.
type SessionsSessionIdDeleteNoContent struct{}

func (*SessionsSessionIdDeleteNoContent) sessionsSessionIdDeleteRes() {}

type SessionsSessionIdDeleteNotFound ErrorResponse

func (*SessionsSessionIdDeleteNotFound) sessionsSessionIdDeleteRes() {}

type SessionsSessionIdDeleteUnauthorized ErrorResponse

func (*SessionsSessionIdDeleteUnauthorized) sessionsSessionIdDeleteRes() {}

// Ref: #/components/schemas/TokenPair
type TokenPair struct {
	// PASETO v4.public.
	AccessToken string `json:"accessToken"`
	// Opaque-секрет. Сервер хранит только его хэш.
	RefreshToken string `json:"refreshToken"`
}

// GetAccessToken returns the value of AccessToken.
func (s *TokenPair) GetAccessToken() string {
	return s.AccessToken
}

// GetRefreshToken returns the value of RefreshToken.
func (s *TokenPair) GetRefreshToken() string {
	return s.RefreshToken
}

// SetAccessToken sets the value of AccessToken.
func (s *TokenPair) SetAccessToken(val string) {
	s.AccessToken = val
}

// SetRefreshToken sets the value of RefreshToken.
func (s *TokenPair) SetRefreshToken(val string) {
	s.RefreshToken = val
}

func (*TokenPair) registrationCompletePostRes() {}
func (*TokenPair) tokenRefreshPostRes()         {}

type TokenRefreshPostBadRequest ErrorResponse

func (*TokenRefreshPostBadRequest) tokenRefreshPostRes() {}

type TokenRefreshPostInternalServerError ErrorResponse

func (*TokenRefreshPostInternalServerError) tokenRefreshPostRes() {}

type TokenRefreshPostReq struct {
	RefreshToken string `json:"refreshToken"`
}

// GetRefreshToken returns the value of RefreshToken.
func (s *TokenRefreshPostReq) GetRefreshToken() string {
	return s.RefreshToken
}

// SetRefreshToken sets the value of RefreshToken.
func (s *TokenRefreshPostReq) SetRefreshToken(val string) {
	s.RefreshToken = val
}

type TokenRefreshPostUnauthorized ErrorResponse

func (*TokenRefreshPostUnauthorized) tokenRefreshPostRes() {}

type WebAuthnAuthenticationResponse jx.Raw

type WebAuthnCreationOptions jx.Raw

type WebAuthnRegistrationResponse jx.Raw

type WebAuthnRequestOptions jx.Raw

// Ref: #/components/schemas/WrappedKeyInput
type WrappedKeyInput struct {
	Scope WrappedKeyScope `json:"scope"`
	// Base64 блоб.
	WrappedDek    []byte `json:"wrappedDek"`
	WrapAlgorithm string `json:"wrapAlgorithm"`
}

// GetScope returns the value of Scope.
func (s *WrappedKeyInput) GetScope() WrappedKeyScope {
	return s.Scope
}

// GetWrappedDek returns the value of WrappedDek.
func (s *WrappedKeyInput) GetWrappedDek() []byte {
	return s.WrappedDek
}

// GetWrapAlgorithm returns the value of WrapAlgorithm.
func (s *WrappedKeyInput) GetWrapAlgorithm() string {
	return s.WrapAlgorithm
}

// SetScope sets the value of Scope.
func (s *WrappedKeyInput) SetScope(val WrappedKeyScope) {
	s.Scope = val
}

// SetWrappedDek sets the value of WrappedDek.
func (s *WrappedKeyInput) SetWrappedDek(val []byte) {
	s.WrappedDek = val
}

// SetWrapAlgorithm sets the value of WrapAlgorithm.
func (s *WrappedKeyInput) SetWrapAlgorithm(val string) {
	s.WrapAlgorithm = val
}

// Ref: #/components/schemas/WrappedKeyOutput
type WrappedKeyOutput struct {
	Scope WrappedKeyScope `json:"scope"`
	// Base64 блоб - сервер отдаёт как есть, никогда не
	// расшифровывает.
	WrappedDek    []byte `json:"wrappedDek"`
	WrapAlgorithm string `json:"wrapAlgorithm"`
}

// GetScope returns the value of Scope.
func (s *WrappedKeyOutput) GetScope() WrappedKeyScope {
	return s.Scope
}

// GetWrappedDek returns the value of WrappedDek.
func (s *WrappedKeyOutput) GetWrappedDek() []byte {
	return s.WrappedDek
}

// GetWrapAlgorithm returns the value of WrapAlgorithm.
func (s *WrappedKeyOutput) GetWrapAlgorithm() string {
	return s.WrapAlgorithm
}

// SetScope sets the value of Scope.
func (s *WrappedKeyOutput) SetScope(val WrappedKeyScope) {
	s.Scope = val
}

// SetWrappedDek sets the value of WrappedDek.
func (s *WrappedKeyOutput) SetWrappedDek(val []byte) {
	s.WrappedDek = val
}

// SetWrapAlgorithm sets the value of WrapAlgorithm.
func (s *WrappedKeyOutput) SetWrapAlgorithm(val string) {
	s.WrapAlgorithm = val
}

// Ref: #/components/schemas/WrappedKeyScope
type WrappedKeyScope string

const (
	WrappedKeyScopeMain  WrappedKeyScope = "main"
	WrappedKeyScopeDecoy WrappedKeyScope = "decoy"
)

// AllValues returns all WrappedKeyScope values.
func (WrappedKeyScope) AllValues() []WrappedKeyScope {
	return []WrappedKeyScope{
		WrappedKeyScopeMain,
		WrappedKeyScopeDecoy,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s WrappedKeyScope) MarshalText() ([]byte, error) {
	switch s {
	case WrappedKeyScopeMain:
		return []byte(s), nil
	case WrappedKeyScopeDecoy:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *WrappedKeyScope) UnmarshalText(data []byte) error {
	switch WrappedKeyScope(data) {
	case WrappedKeyScopeMain:
		*s = WrappedKeyScopeMain
		return nil
	case WrappedKeyScopeDecoy:
		*s = WrappedKeyScopeDecoy
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
