// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// AdminUsersUserIdRevokeChainPostParams is parameters of POST /admin/users/{userId}/revoke-chain operation.
type AdminUsersUserIdRevokeChainPostParams struct {
	// Идентификатор пользователя.
	UserId uuid.UUID
}

func unpackAdminUsersUserIdRevokeChainPostParams(packed middleware.Parameters) (params AdminUsersUserIdRevokeChainPostParams) {
	{
		key := middleware.ParameterKey{
			Name: "userId",
			In:   "path",
		}
		params.UserId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeAdminUsersUserIdRevokeChainPostParams(args [1]string, argsEscaped bool, r *http.Request) (params AdminUsersUserIdRevokeChainPostParams, _ error) {
	// Decode path: userId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "userId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.UserId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "userId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// SessionsSessionIdDeleteParams is parameters of DELETE /sessions/{sessionId} operation.
type SessionsSessionIdDeleteParams struct {
	// Идентификатор refresh-сессии.
	SessionId uuid.UUID
}

func unpackSessionsSessionIdDeleteParams(packed middleware.Parameters) (params SessionsSessionIdDeleteParams) {
	{
		key := middleware.ParameterKey{
			Name: "sessionId",
			In:   "path",
		}
		params.SessionId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeSessionsSessionIdDeleteParams(args [1]string, argsEscaped bool, r *http.Request) (params SessionsSessionIdDeleteParams, _ error) {
	// Decode path: sessionId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "sessionId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.SessionId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sessionId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
