// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	AdminUsersUserIdRevokeChainPostOperation OperationName = "AdminUsersUserIdRevokeChainPost"
	AuthVerifyGetOperation                   OperationName = "AuthVerifyGet"
	InvitesPostOperation                     OperationName = "InvitesPost"
	LoginBeginPostOperation                  OperationName = "LoginBeginPost"
	LoginPostOperation                       OperationName = "LoginPost"
	RegistrationBeginPostOperation           OperationName = "RegistrationBeginPost"
	RegistrationCompletePostOperation        OperationName = "RegistrationCompletePost"
	SessionsSessionIdDeleteOperation         OperationName = "SessionsSessionIdDelete"
	TokenRefreshPostOperation                OperationName = "TokenRefreshPost"
)
