// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AdminUsersUserIdRevokeChainPost implements POST /admin/users/{userId}/revoke-chain operation.
	//
	// Каскадный отзыв сессий по цепочке приглашений.
	//
	// POST /admin/users/{userId}/revoke-chain
	AdminUsersUserIdRevokeChainPost(ctx context.Context, params AdminUsersUserIdRevokeChainPostParams) (AdminUsersUserIdRevokeChainPostRes, error)
	// AuthVerifyGet implements AuthVerifyGet operation.
	//
	// Проверяет Bearer access token для Traefik ForwardAuth.
	//
	// GET /auth/verify
	AuthVerifyGet(ctx context.Context) (AuthVerifyGetRes, error)
	// InvitesPost implements POST /invites operation.
	//
	// Создаёт инвайт от лица текущего авторизованного
	// пользователя. UserID берётся из Bearer токена (PASETO) в middleware.
	//
	// POST /invites
	InvitesPost(ctx context.Context) (InvitesPostRes, error)
	// LoginBeginPost implements POST /login/begin operation.
	//
	// Начать вход.
	//
	// POST /login/begin
	LoginBeginPost(ctx context.Context) (LoginBeginPostRes, error)
	// LoginPost implements POST /login operation.
	//
	// Завершить вход.
	//
	// POST /login
	LoginPost(ctx context.Context, req *LoginPostReq) (LoginPostRes, error)
	// RegistrationBeginPost implements POST /registration/begin operation.
	//
	// Начать регистрацию по инвайт-коду.
	//
	// POST /registration/begin
	RegistrationBeginPost(ctx context.Context, req *RegistrationBeginPostReq) (RegistrationBeginPostRes, error)
	// RegistrationCompletePost implements POST /registration/complete operation.
	//
	// Завершает регистрацию. IP-адрес извлекается из
	// HTTP-запроса на уровне хендлера.
	//
	// POST /registration/complete
	RegistrationCompletePost(ctx context.Context, req *RegistrationCompletePostReq) (RegistrationCompletePostRes, error)
	// SessionsSessionIdDelete implements DELETE /sessions/{sessionId} operation.
	//
	// Отзыв конкретной сессии по её ID.
	//
	// DELETE /sessions/{sessionId}
	SessionsSessionIdDelete(ctx context.Context, params SessionsSessionIdDeleteParams) (SessionsSessionIdDeleteRes, error)
	// TokenRefreshPost implements POST /token/refresh operation.
	//
	// Обновить access-токен.
	//
	// POST /token/refresh
	TokenRefreshPost(ctx context.Context, req *TokenRefreshPostReq) (TokenRefreshPostRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
