// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewBeginLogin creates a new instance of BeginLogin. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBeginLogin(t interface {
	mock.TestingT
	Cleanup(func())
}) *BeginLogin {
	mock := &BeginLogin{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BeginLogin is an autogenerated mock type for the BeginLogin type
type BeginLogin struct {
	mock.Mock
}

type BeginLogin_Expecter struct {
	mock *mock.Mock
}

func (_m *BeginLogin) EXPECT() *BeginLogin_Expecter {
	return &BeginLogin_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type BeginLogin
func (_mock *BeginLogin) Execute(ctx context.Context) (string, []byte, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, []byte, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) []byte); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// BeginLogin_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type BeginLogin_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *BeginLogin_Expecter) Execute(ctx any) *BeginLogin_Execute_Call {
	return &BeginLogin_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *BeginLogin_Execute_Call) Run(run func(ctx context.Context)) *BeginLogin_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *BeginLogin_Execute_Call) Return(token string, opts []byte, err error) *BeginLogin_Execute_Call {
	_c.Call.Return(token, opts, err)
	return _c
}

func (_c *BeginLogin_Execute_Call) RunAndReturn(run func(ctx context.Context) (string, []byte, error)) *BeginLogin_Execute_Call {
	_c.Call.Return(run)
	return _c
}
