// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewBeginInviteRegistration creates a new instance of BeginInviteRegistration. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBeginInviteRegistration(t interface {
	mock.TestingT
	Cleanup(func())
}) *BeginInviteRegistration {
	mock := &BeginInviteRegistration{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BeginInviteRegistration is an autogenerated mock type for the BeginInviteRegistration type
type BeginInviteRegistration struct {
	mock.Mock
}

type BeginInviteRegistration_Expecter struct {
	mock *mock.Mock
}

func (_m *BeginInviteRegistration) EXPECT() *BeginInviteRegistration_Expecter {
	return &BeginInviteRegistration_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type BeginInviteRegistration
func (_mock *BeginInviteRegistration) Execute(ctx context.Context, inviteCode string) (string, []byte, error) {
	ret := _mock.Called(ctx, inviteCode)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, []byte, error)); ok {
		return returnFunc(ctx, inviteCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, inviteCode)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) []byte); ok {
		r1 = returnFunc(ctx, inviteCode)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, inviteCode)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// BeginInviteRegistration_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type BeginInviteRegistration_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - inviteCode string
func (_e *BeginInviteRegistration_Expecter) Execute(ctx any, inviteCode any) *BeginInviteRegistration_Execute_Call {
	return &BeginInviteRegistration_Execute_Call{Call: _e.mock.On("Execute", ctx, inviteCode)}
}

func (_c *BeginInviteRegistration_Execute_Call) Run(run func(ctx context.Context, inviteCode string)) *BeginInviteRegistration_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BeginInviteRegistration_Execute_Call) Return(challengeToken string, creationOptions []byte, err error) *BeginInviteRegistration_Execute_Call {
	_c.Call.Return(challengeToken, creationOptions, err)
	return _c
}

func (_c *BeginInviteRegistration_Execute_Call) RunAndReturn(run func(ctx context.Context, inviteCode string) (string, []byte, error)) *BeginInviteRegistration_Execute_Call {
	_c.Call.Return(run)
	return _c
}
