// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/whicu/hsa/internal/domain/user"
)

// NewCreateInvite creates a new instance of CreateInvite. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateInvite(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateInvite {
	mock := &CreateInvite{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CreateInvite is an autogenerated mock type for the CreateInvite type
type CreateInvite struct {
	mock.Mock
}

type CreateInvite_Expecter struct {
	mock *mock.Mock
}

func (_m *CreateInvite) EXPECT() *CreateInvite_Expecter {
	return &CreateInvite_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type CreateInvite
func (_mock *CreateInvite) Execute(ctx context.Context, createdBy user.UserID) (string, time.Time, error) {
	ret := _mock.Called(ctx, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 time.Time
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.UserID) (string, time.Time, error)); ok {
		return returnFunc(ctx, createdBy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.UserID) string); ok {
		r0 = returnFunc(ctx, createdBy)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.UserID) time.Time); ok {
		r1 = returnFunc(ctx, createdBy)
	} else {
		r1 = ret.Get(1).(time.Time)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, user.UserID) error); ok {
		r2 = returnFunc(ctx, createdBy)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// CreateInvite_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type CreateInvite_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - createdBy user.UserID
func (_e *CreateInvite_Expecter) Execute(ctx any, createdBy any) *CreateInvite_Execute_Call {
	return &CreateInvite_Execute_Call{Call: _e.mock.On("Execute", ctx, createdBy)}
}

func (_c *CreateInvite_Execute_Call) Run(run func(ctx context.Context, createdBy user.UserID)) *CreateInvite_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.UserID
		if args[1] != nil {
			arg1 = args[1].(user.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CreateInvite_Execute_Call) Return(code string, expiresAt time.Time, err error) *CreateInvite_Execute_Call {
	_c.Call.Return(code, expiresAt, err)
	return _c
}

func (_c *CreateInvite_Execute_Call) RunAndReturn(run func(ctx context.Context, createdBy user.UserID) (string, time.Time, error)) *CreateInvite_Execute_Call {
	_c.Call.Return(run)
	return _c
}
