// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/whicu/hsa/internal/application"
)

// NewFinishInviteRegistration creates a new instance of FinishInviteRegistration. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFinishInviteRegistration(t interface {
	mock.TestingT
	Cleanup(func())
}) *FinishInviteRegistration {
	mock := &FinishInviteRegistration{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FinishInviteRegistration is an autogenerated mock type for the FinishInviteRegistration type
type FinishInviteRegistration struct {
	mock.Mock
}

type FinishInviteRegistration_Expecter struct {
	mock *mock.Mock
}

func (_m *FinishInviteRegistration) EXPECT() *FinishInviteRegistration_Expecter {
	return &FinishInviteRegistration_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type FinishInviteRegistration
func (_mock *FinishInviteRegistration) Execute(ctx context.Context, in application.FinishInviteRegistrationInput) (*application.FinishInviteRegistrationOutput, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *application.FinishInviteRegistrationOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, application.FinishInviteRegistrationInput) (*application.FinishInviteRegistrationOutput, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, application.FinishInviteRegistrationInput) *application.FinishInviteRegistrationOutput); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*application.FinishInviteRegistrationOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, application.FinishInviteRegistrationInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FinishInviteRegistration_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type FinishInviteRegistration_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in application.FinishInviteRegistrationInput
func (_e *FinishInviteRegistration_Expecter) Execute(ctx any, in any) *FinishInviteRegistration_Execute_Call {
	return &FinishInviteRegistration_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *FinishInviteRegistration_Execute_Call) Run(run func(ctx context.Context, in application.FinishInviteRegistrationInput)) *FinishInviteRegistration_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 application.FinishInviteRegistrationInput
		if args[1] != nil {
			arg1 = args[1].(application.FinishInviteRegistrationInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FinishInviteRegistration_Execute_Call) Return(finishInviteRegistrationOutput *application.FinishInviteRegistrationOutput, err error) *FinishInviteRegistration_Execute_Call {
	_c.Call.Return(finishInviteRegistrationOutput, err)
	return _c
}

func (_c *FinishInviteRegistration_Execute_Call) RunAndReturn(run func(ctx context.Context, in application.FinishInviteRegistrationInput) (*application.FinishInviteRegistrationOutput, error)) *FinishInviteRegistration_Execute_Call {
	_c.Call.Return(run)
	return _c
}
