// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/whicu/hsa/internal/application"
)

// NewFinishLogin creates a new instance of FinishLogin. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFinishLogin(t interface {
	mock.TestingT
	Cleanup(func())
}) *FinishLogin {
	mock := &FinishLogin{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FinishLogin is an autogenerated mock type for the FinishLogin type
type FinishLogin struct {
	mock.Mock
}

type FinishLogin_Expecter struct {
	mock *mock.Mock
}

func (_m *FinishLogin) EXPECT() *FinishLogin_Expecter {
	return &FinishLogin_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type FinishLogin
func (_mock *FinishLogin) Execute(ctx context.Context, in application.LoginInput) (*application.LoginOutput, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *application.LoginOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, application.LoginInput) (*application.LoginOutput, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, application.LoginInput) *application.LoginOutput); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*application.LoginOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, application.LoginInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FinishLogin_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type FinishLogin_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in application.LoginInput
func (_e *FinishLogin_Expecter) Execute(ctx any, in any) *FinishLogin_Execute_Call {
	return &FinishLogin_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *FinishLogin_Execute_Call) Run(run func(ctx context.Context, in application.LoginInput)) *FinishLogin_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 application.LoginInput
		if args[1] != nil {
			arg1 = args[1].(application.LoginInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FinishLogin_Execute_Call) Return(loginOutput *application.LoginOutput, err error) *FinishLogin_Execute_Call {
	_c.Call.Return(loginOutput, err)
	return _c
}

func (_c *FinishLogin_Execute_Call) RunAndReturn(run func(ctx context.Context, in application.LoginInput) (*application.LoginOutput, error)) *FinishLogin_Execute_Call {
	_c.Call.Return(run)
	return _c
}
