// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewRefreshAccessToken creates a new instance of RefreshAccessToken. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshAccessToken(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshAccessToken {
	mock := &RefreshAccessToken{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RefreshAccessToken is an autogenerated mock type for the RefreshAccessToken type
type RefreshAccessToken struct {
	mock.Mock
}

type RefreshAccessToken_Expecter struct {
	mock *mock.Mock
}

func (_m *RefreshAccessToken) EXPECT() *RefreshAccessToken_Expecter {
	return &RefreshAccessToken_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type RefreshAccessToken
func (_mock *RefreshAccessToken) Execute(ctx context.Context, rawRefreshToken string) (string, string, error) {
	ret := _mock.Called(ctx, rawRefreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, string, error)); ok {
		return returnFunc(ctx, rawRefreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, rawRefreshToken)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = returnFunc(ctx, rawRefreshToken)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, rawRefreshToken)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// RefreshAccessToken_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type RefreshAccessToken_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - rawRefreshToken string
func (_e *RefreshAccessToken_Expecter) Execute(ctx any, rawRefreshToken any) *RefreshAccessToken_Execute_Call {
	return &RefreshAccessToken_Execute_Call{Call: _e.mock.On("Execute", ctx, rawRefreshToken)}
}

func (_c *RefreshAccessToken_Execute_Call) Run(run func(ctx context.Context, rawRefreshToken string)) *RefreshAccessToken_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RefreshAccessToken_Execute_Call) Return(accessToken string, refreshToken string, err error) *RefreshAccessToken_Execute_Call {
	_c.Call.Return(accessToken, refreshToken, err)
	return _c
}

func (_c *RefreshAccessToken_Execute_Call) RunAndReturn(run func(ctx context.Context, rawRefreshToken string) (string, string, error)) *RefreshAccessToken_Execute_Call {
	_c.Call.Return(run)
	return _c
}
