// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/whicu/hsa/internal/domain/user"
)

// NewRevokeCompromisedChain creates a new instance of RevokeCompromisedChain. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRevokeCompromisedChain(t interface {
	mock.TestingT
	Cleanup(func())
}) *RevokeCompromisedChain {
	mock := &RevokeCompromisedChain{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RevokeCompromisedChain is an autogenerated mock type for the RevokeCompromisedChain type
type RevokeCompromisedChain struct {
	mock.Mock
}

type RevokeCompromisedChain_Expecter struct {
	mock *mock.Mock
}

func (_m *RevokeCompromisedChain) EXPECT() *RevokeCompromisedChain_Expecter {
	return &RevokeCompromisedChain_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type RevokeCompromisedChain
func (_mock *RevokeCompromisedChain) Execute(ctx context.Context, compromisedUserID user.UserID) error {
	ret := _mock.Called(ctx, compromisedUserID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.UserID) error); ok {
		r0 = returnFunc(ctx, compromisedUserID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RevokeCompromisedChain_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type RevokeCompromisedChain_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - compromisedUserID user.UserID
func (_e *RevokeCompromisedChain_Expecter) Execute(ctx any, compromisedUserID any) *RevokeCompromisedChain_Execute_Call {
	return &RevokeCompromisedChain_Execute_Call{Call: _e.mock.On("Execute", ctx, compromisedUserID)}
}

func (_c *RevokeCompromisedChain_Execute_Call) Run(run func(ctx context.Context, compromisedUserID user.UserID)) *RevokeCompromisedChain_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.UserID
		if args[1] != nil {
			arg1 = args[1].(user.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RevokeCompromisedChain_Execute_Call) Return(err error) *RevokeCompromisedChain_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RevokeCompromisedChain_Execute_Call) RunAndReturn(run func(ctx context.Context, compromisedUserID user.UserID) error) *RevokeCompromisedChain_Execute_Call {
	_c.Call.Return(run)
	return _c
}
