// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/whicu/hsa/internal/domain/session"
	"github.com/whicu/hsa/internal/domain/user"
)

// NewRevokeSession creates a new instance of RevokeSession. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRevokeSession(t interface {
	mock.TestingT
	Cleanup(func())
}) *RevokeSession {
	mock := &RevokeSession{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RevokeSession is an autogenerated mock type for the RevokeSession type
type RevokeSession struct {
	mock.Mock
}

type RevokeSession_Expecter struct {
	mock *mock.Mock
}

func (_m *RevokeSession) EXPECT() *RevokeSession_Expecter {
	return &RevokeSession_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type RevokeSession
func (_mock *RevokeSession) Execute(ctx context.Context, sessionID session.RefreshTokenID, requestingUserID user.UserID) error {
	ret := _mock.Called(ctx, sessionID, requestingUserID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, session.RefreshTokenID, user.UserID) error); ok {
		r0 = returnFunc(ctx, sessionID, requestingUserID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RevokeSession_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type RevokeSession_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID session.RefreshTokenID
//   - requestingUserID user.UserID
func (_e *RevokeSession_Expecter) Execute(ctx any, sessionID any, requestingUserID any) *RevokeSession_Execute_Call {
	return &RevokeSession_Execute_Call{Call: _e.mock.On("Execute", ctx, sessionID, requestingUserID)}
}

func (_c *RevokeSession_Execute_Call) Run(run func(ctx context.Context, sessionID session.RefreshTokenID, requestingUserID user.UserID)) *RevokeSession_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 session.RefreshTokenID
		if args[1] != nil {
			arg1 = args[1].(session.RefreshTokenID)
		}
		var arg2 user.UserID
		if args[2] != nil {
			arg2 = args[2].(user.UserID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RevokeSession_Execute_Call) Return(err error) *RevokeSession_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RevokeSession_Execute_Call) RunAndReturn(run func(ctx context.Context, sessionID session.RefreshTokenID, requestingUserID user.UserID) error) *RevokeSession_Execute_Call {
	_c.Call.Return(run)
	return _c
}
