// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	api "github.com/whicu/hsa/api/http"
)

// NewSecurityHandler creates a new instance of SecurityHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecurityHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecurityHandler {
	mock := &SecurityHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SecurityHandler is an autogenerated mock type for the SecurityHandler type
type SecurityHandler struct {
	mock.Mock
}

type SecurityHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *SecurityHandler) EXPECT() *SecurityHandler_Expecter {
	return &SecurityHandler_Expecter{mock: &_m.Mock}
}

// HandleBearerAuth provides a mock function for the type SecurityHandler
func (_mock *SecurityHandler) HandleBearerAuth(ctx context.Context, operationName api.OperationName, t api.BearerAuth) (context.Context, error) {
	ret := _mock.Called(ctx, operationName, t)

	if len(ret) == 0 {
		panic("no return value specified for HandleBearerAuth")
	}

	var r0 context.Context
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, api.OperationName, api.BearerAuth) (context.Context, error)); ok {
		return returnFunc(ctx, operationName, t)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, api.OperationName, api.BearerAuth) context.Context); ok {
		r0 = returnFunc(ctx, operationName, t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, api.OperationName, api.BearerAuth) error); ok {
		r1 = returnFunc(ctx, operationName, t)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SecurityHandler_HandleBearerAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleBearerAuth'
type SecurityHandler_HandleBearerAuth_Call struct {
	*mock.Call
}

// HandleBearerAuth is a helper method to define mock.On call
//   - ctx context.Context
//   - operationName api.OperationName
//   - t api.BearerAuth
func (_e *SecurityHandler_Expecter) HandleBearerAuth(ctx any, operationName any, t any) *SecurityHandler_HandleBearerAuth_Call {
	return &SecurityHandler_HandleBearerAuth_Call{Call: _e.mock.On("HandleBearerAuth", ctx, operationName, t)}
}

func (_c *SecurityHandler_HandleBearerAuth_Call) Run(run func(ctx context.Context, operationName api.OperationName, t api.BearerAuth)) *SecurityHandler_HandleBearerAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 api.OperationName
		if args[1] != nil {
			arg1 = args[1].(api.OperationName)
		}
		var arg2 api.BearerAuth
		if args[2] != nil {
			arg2 = args[2].(api.BearerAuth)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SecurityHandler_HandleBearerAuth_Call) Return(context1 context.Context, err error) *SecurityHandler_HandleBearerAuth_Call {
	_c.Call.Return(context1, err)
	return _c
}

func (_c *SecurityHandler_HandleBearerAuth_Call) RunAndReturn(run func(ctx context.Context, operationName api.OperationName, t api.BearerAuth) (context.Context, error)) *SecurityHandler_HandleBearerAuth_Call {
	_c.Call.Return(run)
	return _c
}
