// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewChallengeCodec creates a new instance of ChallengeCodec. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChallengeCodec(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChallengeCodec {
	mock := &ChallengeCodec{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ChallengeCodec is an autogenerated mock type for the ChallengeCodec type
type ChallengeCodec struct {
	mock.Mock
}

type ChallengeCodec_Expecter struct {
	mock *mock.Mock
}

func (_m *ChallengeCodec) EXPECT() *ChallengeCodec_Expecter {
	return &ChallengeCodec_Expecter{mock: &_m.Mock}
}

// Decode provides a mock function for the type ChallengeCodec
func (_mock *ChallengeCodec) Decode(token string, out any) error {
	ret := _mock.Called(token, out)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, any) error); ok {
		r0 = returnFunc(token, out)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ChallengeCodec_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type ChallengeCodec_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - token string
//   - out any
func (_e *ChallengeCodec_Expecter) Decode(token any, out any) *ChallengeCodec_Decode_Call {
	return &ChallengeCodec_Decode_Call{Call: _e.mock.On("Decode", token, out)}
}

func (_c *ChallengeCodec_Decode_Call) Run(run func(token string, out any)) *ChallengeCodec_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ChallengeCodec_Decode_Call) Return(err error) *ChallengeCodec_Decode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ChallengeCodec_Decode_Call) RunAndReturn(run func(token string, out any) error) *ChallengeCodec_Decode_Call {
	_c.Call.Return(run)
	return _c
}

// Encode provides a mock function for the type ChallengeCodec
func (_mock *ChallengeCodec) Encode(payload any, ttl time.Duration) (string, error) {
	ret := _mock.Called(payload, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Encode")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(any, time.Duration) (string, error)); ok {
		return returnFunc(payload, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(any, time.Duration) string); ok {
		r0 = returnFunc(payload, ttl)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(any, time.Duration) error); ok {
		r1 = returnFunc(payload, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ChallengeCodec_Encode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encode'
type ChallengeCodec_Encode_Call struct {
	*mock.Call
}

// Encode is a helper method to define mock.On call
//   - payload any
//   - ttl time.Duration
func (_e *ChallengeCodec_Expecter) Encode(payload any, ttl any) *ChallengeCodec_Encode_Call {
	return &ChallengeCodec_Encode_Call{Call: _e.mock.On("Encode", payload, ttl)}
}

func (_c *ChallengeCodec_Encode_Call) Run(run func(payload any, ttl time.Duration)) *ChallengeCodec_Encode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ChallengeCodec_Encode_Call) Return(token string, err error) *ChallengeCodec_Encode_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *ChallengeCodec_Encode_Call) RunAndReturn(run func(payload any, ttl time.Duration) (string, error)) *ChallengeCodec_Encode_Call {
	_c.Call.Return(run)
	return _c
}
