// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/whicu/hsa/internal/domain/credential"
	"github.com/whicu/hsa/internal/domain/user"
)

// NewCredentialsProvider creates a new instance of CredentialsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCredentialsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *CredentialsProvider {
	mock := &CredentialsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CredentialsProvider is an autogenerated mock type for the CredentialsProvider type
type CredentialsProvider struct {
	mock.Mock
}

type CredentialsProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *CredentialsProvider) EXPECT() *CredentialsProvider_Expecter {
	return &CredentialsProvider_Expecter{mock: &_m.Mock}
}

// FindByUserID provides a mock function for the type CredentialsProvider
func (_mock *CredentialsProvider) FindByUserID(ctx context.Context, userID user.UserID) ([]*credential.Credential, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []*credential.Credential
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.UserID) ([]*credential.Credential, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.UserID) []*credential.Credential); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*credential.Credential)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.UserID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CredentialsProvider_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type CredentialsProvider_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID user.UserID
func (_e *CredentialsProvider_Expecter) FindByUserID(ctx any, userID any) *CredentialsProvider_FindByUserID_Call {
	return &CredentialsProvider_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *CredentialsProvider_FindByUserID_Call) Run(run func(ctx context.Context, userID user.UserID)) *CredentialsProvider_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.UserID
		if args[1] != nil {
			arg1 = args[1].(user.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CredentialsProvider_FindByUserID_Call) Return(credentials []*credential.Credential, err error) *CredentialsProvider_FindByUserID_Call {
	_c.Call.Return(credentials, err)
	return _c
}

func (_c *CredentialsProvider_FindByUserID_Call) RunAndReturn(run func(ctx context.Context, userID user.UserID) ([]*credential.Credential, error)) *CredentialsProvider_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}
