// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/whicu/hsa/internal/domain/user"
)

// NewActiveInviteCounter creates a new instance of ActiveInviteCounter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActiveInviteCounter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActiveInviteCounter {
	mock := &ActiveInviteCounter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ActiveInviteCounter is an autogenerated mock type for the ActiveInviteCounter type
type ActiveInviteCounter struct {
	mock.Mock
}

type ActiveInviteCounter_Expecter struct {
	mock *mock.Mock
}

func (_m *ActiveInviteCounter) EXPECT() *ActiveInviteCounter_Expecter {
	return &ActiveInviteCounter_Expecter{mock: &_m.Mock}
}

// CountActiveByUser provides a mock function for the type ActiveInviteCounter
func (_mock *ActiveInviteCounter) CountActiveByUser(ctx context.Context, userID user.UserID, now time.Time) (int, error) {
	ret := _mock.Called(ctx, userID, now)

	if len(ret) == 0 {
		panic("no return value specified for CountActiveByUser")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.UserID, time.Time) (int, error)); ok {
		return returnFunc(ctx, userID, now)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.UserID, time.Time) int); ok {
		r0 = returnFunc(ctx, userID, now)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.UserID, time.Time) error); ok {
		r1 = returnFunc(ctx, userID, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ActiveInviteCounter_CountActiveByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountActiveByUser'
type ActiveInviteCounter_CountActiveByUser_Call struct {
	*mock.Call
}

// CountActiveByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID user.UserID
//   - now time.Time
func (_e *ActiveInviteCounter_Expecter) CountActiveByUser(ctx any, userID any, now any) *ActiveInviteCounter_CountActiveByUser_Call {
	return &ActiveInviteCounter_CountActiveByUser_Call{Call: _e.mock.On("CountActiveByUser", ctx, userID, now)}
}

func (_c *ActiveInviteCounter_CountActiveByUser_Call) Run(run func(ctx context.Context, userID user.UserID, now time.Time)) *ActiveInviteCounter_CountActiveByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.UserID
		if args[1] != nil {
			arg1 = args[1].(user.UserID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ActiveInviteCounter_CountActiveByUser_Call) Return(n int, err error) *ActiveInviteCounter_CountActiveByUser_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *ActiveInviteCounter_CountActiveByUser_Call) RunAndReturn(run func(ctx context.Context, userID user.UserID, now time.Time) (int, error)) *ActiveInviteCounter_CountActiveByUser_Call {
	_c.Call.Return(run)
	return _c
}
