// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/whicu/hsa/internal/domain/session"
	"github.com/whicu/hsa/internal/domain/user"
)

// NewActiveSessionsFinder creates a new instance of ActiveSessionsFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActiveSessionsFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActiveSessionsFinder {
	mock := &ActiveSessionsFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ActiveSessionsFinder is an autogenerated mock type for the ActiveSessionsFinder type
type ActiveSessionsFinder struct {
	mock.Mock
}

type ActiveSessionsFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *ActiveSessionsFinder) EXPECT() *ActiveSessionsFinder_Expecter {
	return &ActiveSessionsFinder_Expecter{mock: &_m.Mock}
}

// FindActiveByUserIDs provides a mock function for the type ActiveSessionsFinder
func (_mock *ActiveSessionsFinder) FindActiveByUserIDs(ctx context.Context, userIDs []user.UserID, now time.Time) ([]*session.RefreshToken, error) {
	ret := _mock.Called(ctx, userIDs, now)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveByUserIDs")
	}

	var r0 []*session.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []user.UserID, time.Time) ([]*session.RefreshToken, error)); ok {
		return returnFunc(ctx, userIDs, now)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []user.UserID, time.Time) []*session.RefreshToken); ok {
		r0 = returnFunc(ctx, userIDs, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*session.RefreshToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []user.UserID, time.Time) error); ok {
		r1 = returnFunc(ctx, userIDs, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ActiveSessionsFinder_FindActiveByUserIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActiveByUserIDs'
type ActiveSessionsFinder_FindActiveByUserIDs_Call struct {
	*mock.Call
}

// FindActiveByUserIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userIDs []user.UserID
//   - now time.Time
func (_e *ActiveSessionsFinder_Expecter) FindActiveByUserIDs(ctx any, userIDs any, now any) *ActiveSessionsFinder_FindActiveByUserIDs_Call {
	return &ActiveSessionsFinder_FindActiveByUserIDs_Call{Call: _e.mock.On("FindActiveByUserIDs", ctx, userIDs, now)}
}

func (_c *ActiveSessionsFinder_FindActiveByUserIDs_Call) Run(run func(ctx context.Context, userIDs []user.UserID, now time.Time)) *ActiveSessionsFinder_FindActiveByUserIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []user.UserID
		if args[1] != nil {
			arg1 = args[1].([]user.UserID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ActiveSessionsFinder_FindActiveByUserIDs_Call) Return(refreshTokens []*session.RefreshToken, err error) *ActiveSessionsFinder_FindActiveByUserIDs_Call {
	_c.Call.Return(refreshTokens, err)
	return _c
}

func (_c *ActiveSessionsFinder_FindActiveByUserIDs_Call) RunAndReturn(run func(ctx context.Context, userIDs []user.UserID, now time.Time) ([]*session.RefreshToken, error)) *ActiveSessionsFinder_FindActiveByUserIDs_Call {
	_c.Call.Return(run)
	return _c
}
