// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/whicu/hsa/internal/application"
)

// NewAuthenticator creates a new instance of Authenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthenticator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Authenticator {
	mock := &Authenticator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Authenticator is an autogenerated mock type for the Authenticator type
type Authenticator struct {
	mock.Mock
}

type Authenticator_Expecter struct {
	mock *mock.Mock
}

func (_m *Authenticator) EXPECT() *Authenticator_Expecter {
	return &Authenticator_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function for the type Authenticator
func (_mock *Authenticator) Begin(ctx context.Context) (string, []byte, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 string
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, []byte, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) []byte); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Authenticator_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type Authenticator_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Authenticator_Expecter) Begin(ctx any) *Authenticator_Begin_Call {
	return &Authenticator_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *Authenticator_Begin_Call) Run(run func(ctx context.Context)) *Authenticator_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Authenticator_Begin_Call) Return(challengeToken string, requestOptions []byte, err error) *Authenticator_Begin_Call {
	_c.Call.Return(challengeToken, requestOptions, err)
	return _c
}

func (_c *Authenticator_Begin_Call) RunAndReturn(run func(ctx context.Context) (string, []byte, error)) *Authenticator_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Finish provides a mock function for the type Authenticator
func (_mock *Authenticator) Finish(ctx context.Context, challengeToken string, response []byte) (application.AuthenticationResult, error) {
	ret := _mock.Called(ctx, challengeToken, response)

	if len(ret) == 0 {
		panic("no return value specified for Finish")
	}

	var r0 application.AuthenticationResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) (application.AuthenticationResult, error)); ok {
		return returnFunc(ctx, challengeToken, response)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) application.AuthenticationResult); ok {
		r0 = returnFunc(ctx, challengeToken, response)
	} else {
		r0 = ret.Get(0).(application.AuthenticationResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = returnFunc(ctx, challengeToken, response)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Authenticator_Finish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Finish'
type Authenticator_Finish_Call struct {
	*mock.Call
}

// Finish is a helper method to define mock.On call
//   - ctx context.Context
//   - challengeToken string
//   - response []byte
func (_e *Authenticator_Expecter) Finish(ctx any, challengeToken any, response any) *Authenticator_Finish_Call {
	return &Authenticator_Finish_Call{Call: _e.mock.On("Finish", ctx, challengeToken, response)}
}

func (_c *Authenticator_Finish_Call) Run(run func(ctx context.Context, challengeToken string, response []byte)) *Authenticator_Finish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Authenticator_Finish_Call) Return(authenticationResult application.AuthenticationResult, err error) *Authenticator_Finish_Call {
	_c.Call.Return(authenticationResult, err)
	return _c
}

func (_c *Authenticator_Finish_Call) RunAndReturn(run func(ctx context.Context, challengeToken string, response []byte) (application.AuthenticationResult, error)) *Authenticator_Finish_Call {
	_c.Call.Return(run)
	return _c
}
