// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/whicu/hsa/internal/domain/credential"
)

// NewCredentialSaver creates a new instance of CredentialSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCredentialSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *CredentialSaver {
	mock := &CredentialSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CredentialSaver is an autogenerated mock type for the CredentialSaver type
type CredentialSaver struct {
	mock.Mock
}

type CredentialSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *CredentialSaver) EXPECT() *CredentialSaver_Expecter {
	return &CredentialSaver_Expecter{mock: &_m.Mock}
}

// Save provides a mock function for the type CredentialSaver
func (_mock *CredentialSaver) Save(ctx context.Context, c *credential.Credential) error {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *credential.Credential) error); ok {
		r0 = returnFunc(ctx, c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CredentialSaver_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type CredentialSaver_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - c *credential.Credential
func (_e *CredentialSaver_Expecter) Save(ctx any, c any) *CredentialSaver_Save_Call {
	return &CredentialSaver_Save_Call{Call: _e.mock.On("Save", ctx, c)}
}

func (_c *CredentialSaver_Save_Call) Run(run func(ctx context.Context, c *credential.Credential)) *CredentialSaver_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *credential.Credential
		if args[1] != nil {
			arg1 = args[1].(*credential.Credential)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CredentialSaver_Save_Call) Return(err error) *CredentialSaver_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CredentialSaver_Save_Call) RunAndReturn(run func(ctx context.Context, c *credential.Credential) error) *CredentialSaver_Save_Call {
	_c.Call.Return(run)
	return _c
}
