// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/whicu/hsa/internal/domain/credential"
	"github.com/whicu/hsa/internal/domain/key"
)

// NewCredentialWrappedKeysFinder creates a new instance of CredentialWrappedKeysFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCredentialWrappedKeysFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *CredentialWrappedKeysFinder {
	mock := &CredentialWrappedKeysFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CredentialWrappedKeysFinder is an autogenerated mock type for the CredentialWrappedKeysFinder type
type CredentialWrappedKeysFinder struct {
	mock.Mock
}

type CredentialWrappedKeysFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *CredentialWrappedKeysFinder) EXPECT() *CredentialWrappedKeysFinder_Expecter {
	return &CredentialWrappedKeysFinder_Expecter{mock: &_m.Mock}
}

// FindByCredentialID provides a mock function for the type CredentialWrappedKeysFinder
func (_mock *CredentialWrappedKeysFinder) FindByCredentialID(ctx context.Context, credentialID credential.CredentialID) ([]*key.WrappedKey, error) {
	ret := _mock.Called(ctx, credentialID)

	if len(ret) == 0 {
		panic("no return value specified for FindByCredentialID")
	}

	var r0 []*key.WrappedKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, credential.CredentialID) ([]*key.WrappedKey, error)); ok {
		return returnFunc(ctx, credentialID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, credential.CredentialID) []*key.WrappedKey); ok {
		r0 = returnFunc(ctx, credentialID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*key.WrappedKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, credential.CredentialID) error); ok {
		r1 = returnFunc(ctx, credentialID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CredentialWrappedKeysFinder_FindByCredentialID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCredentialID'
type CredentialWrappedKeysFinder_FindByCredentialID_Call struct {
	*mock.Call
}

// FindByCredentialID is a helper method to define mock.On call
//   - ctx context.Context
//   - credentialID credential.CredentialID
func (_e *CredentialWrappedKeysFinder_Expecter) FindByCredentialID(ctx any, credentialID any) *CredentialWrappedKeysFinder_FindByCredentialID_Call {
	return &CredentialWrappedKeysFinder_FindByCredentialID_Call{Call: _e.mock.On("FindByCredentialID", ctx, credentialID)}
}

func (_c *CredentialWrappedKeysFinder_FindByCredentialID_Call) Run(run func(ctx context.Context, credentialID credential.CredentialID)) *CredentialWrappedKeysFinder_FindByCredentialID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 credential.CredentialID
		if args[1] != nil {
			arg1 = args[1].(credential.CredentialID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CredentialWrappedKeysFinder_FindByCredentialID_Call) Return(wrappedKeys []*key.WrappedKey, err error) *CredentialWrappedKeysFinder_FindByCredentialID_Call {
	_c.Call.Return(wrappedKeys, err)
	return _c
}

func (_c *CredentialWrappedKeysFinder_FindByCredentialID_Call) RunAndReturn(run func(ctx context.Context, credentialID credential.CredentialID) ([]*key.WrappedKey, error)) *CredentialWrappedKeysFinder_FindByCredentialID_Call {
	_c.Call.Return(run)
	return _c
}
