// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/whicu/hsa/internal/domain/credential"
)

// NewCredentialFinder creates a new instance of CredentialFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCredentialFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *CredentialFinder {
	mock := &CredentialFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CredentialFinder is an autogenerated mock type for the CredentialFinder type
type CredentialFinder struct {
	mock.Mock
}

type CredentialFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *CredentialFinder) EXPECT() *CredentialFinder_Expecter {
	return &CredentialFinder_Expecter{mock: &_m.Mock}
}

// FindByExternalID provides a mock function for the type CredentialFinder
func (_mock *CredentialFinder) FindByExternalID(ctx context.Context, externalID []byte) (*credential.Credential, error) {
	ret := _mock.Called(ctx, externalID)

	if len(ret) == 0 {
		panic("no return value specified for FindByExternalID")
	}

	var r0 *credential.Credential
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (*credential.Credential, error)); ok {
		return returnFunc(ctx, externalID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) *credential.Credential); ok {
		r0 = returnFunc(ctx, externalID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*credential.Credential)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, externalID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CredentialFinder_FindByExternalID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByExternalID'
type CredentialFinder_FindByExternalID_Call struct {
	*mock.Call
}

// FindByExternalID is a helper method to define mock.On call
//   - ctx context.Context
//   - externalID []byte
func (_e *CredentialFinder_Expecter) FindByExternalID(ctx any, externalID any) *CredentialFinder_FindByExternalID_Call {
	return &CredentialFinder_FindByExternalID_Call{Call: _e.mock.On("FindByExternalID", ctx, externalID)}
}

func (_c *CredentialFinder_FindByExternalID_Call) Run(run func(ctx context.Context, externalID []byte)) *CredentialFinder_FindByExternalID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CredentialFinder_FindByExternalID_Call) Return(credential1 *credential.Credential, err error) *CredentialFinder_FindByExternalID_Call {
	_c.Call.Return(credential1, err)
	return _c
}

func (_c *CredentialFinder_FindByExternalID_Call) RunAndReturn(run func(ctx context.Context, externalID []byte) (*credential.Credential, error)) *CredentialFinder_FindByExternalID_Call {
	_c.Call.Return(run)
	return _c
}
