// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewHashGenerator creates a new instance of HashGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHashGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *HashGenerator {
	mock := &HashGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HashGenerator is an autogenerated mock type for the HashGenerator type
type HashGenerator struct {
	mock.Mock
}

type HashGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *HashGenerator) EXPECT() *HashGenerator_Expecter {
	return &HashGenerator_Expecter{mock: &_m.Mock}
}

// GenerateHash provides a mock function for the type HashGenerator
func (_mock *HashGenerator) GenerateHash(raw string) (string, error) {
	ret := _mock.Called(raw)

	if len(ret) == 0 {
		panic("no return value specified for GenerateHash")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(raw)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(raw)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(raw)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HashGenerator_GenerateHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateHash'
type HashGenerator_GenerateHash_Call struct {
	*mock.Call
}

// GenerateHash is a helper method to define mock.On call
//   - raw string
func (_e *HashGenerator_Expecter) GenerateHash(raw any) *HashGenerator_GenerateHash_Call {
	return &HashGenerator_GenerateHash_Call{Call: _e.mock.On("GenerateHash", raw)}
}

func (_c *HashGenerator_GenerateHash_Call) Run(run func(raw string)) *HashGenerator_GenerateHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HashGenerator_GenerateHash_Call) Return(s string, err error) *HashGenerator_GenerateHash_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *HashGenerator_GenerateHash_Call) RunAndReturn(run func(raw string) (string, error)) *HashGenerator_GenerateHash_Call {
	_c.Call.Return(run)
	return _c
}
