// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewIDGenerator creates a new instance of IDGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDGenerator {
	mock := &IDGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IDGenerator is an autogenerated mock type for the IDGenerator type
type IDGenerator struct {
	mock.Mock
}

type IDGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *IDGenerator) EXPECT() *IDGenerator_Expecter {
	return &IDGenerator_Expecter{mock: &_m.Mock}
}

// NewID provides a mock function for the type IDGenerator
func (_mock *IDGenerator) NewID() uuid.UUID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewID")
	}

	var r0 uuid.UUID
	if returnFunc, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	return r0
}

// IDGenerator_NewID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewID'
type IDGenerator_NewID_Call struct {
	*mock.Call
}

// NewID is a helper method to define mock.On call
func (_e *IDGenerator_Expecter) NewID() *IDGenerator_NewID_Call {
	return &IDGenerator_NewID_Call{Call: _e.mock.On("NewID")}
}

func (_c *IDGenerator_NewID_Call) Run(run func()) *IDGenerator_NewID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IDGenerator_NewID_Call) Return(uUID uuid.UUID) *IDGenerator_NewID_Call {
	_c.Call.Return(uUID)
	return _c
}

func (_c *IDGenerator_NewID_Call) RunAndReturn(run func() uuid.UUID) *IDGenerator_NewID_Call {
	_c.Call.Return(run)
	return _c
}
