// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/whicu/hsa/internal/domain/invite"
)

// NewInviteFinderByID creates a new instance of InviteFinderByID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInviteFinderByID(t interface {
	mock.TestingT
	Cleanup(func())
}) *InviteFinderByID {
	mock := &InviteFinderByID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InviteFinderByID is an autogenerated mock type for the InviteFinderByID type
type InviteFinderByID struct {
	mock.Mock
}

type InviteFinderByID_Expecter struct {
	mock *mock.Mock
}

func (_m *InviteFinderByID) EXPECT() *InviteFinderByID_Expecter {
	return &InviteFinderByID_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type InviteFinderByID
func (_mock *InviteFinderByID) FindByID(ctx context.Context, id invite.InviteID) (*invite.Invite, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *invite.Invite
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, invite.InviteID) (*invite.Invite, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, invite.InviteID) *invite.Invite); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*invite.Invite)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, invite.InviteID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InviteFinderByID_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type InviteFinderByID_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id invite.InviteID
func (_e *InviteFinderByID_Expecter) FindByID(ctx any, id any) *InviteFinderByID_FindByID_Call {
	return &InviteFinderByID_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *InviteFinderByID_FindByID_Call) Run(run func(ctx context.Context, id invite.InviteID)) *InviteFinderByID_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 invite.InviteID
		if args[1] != nil {
			arg1 = args[1].(invite.InviteID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InviteFinderByID_FindByID_Call) Return(invite1 *invite.Invite, err error) *InviteFinderByID_FindByID_Call {
	_c.Call.Return(invite1, err)
	return _c
}

func (_c *InviteFinderByID_FindByID_Call) RunAndReturn(run func(ctx context.Context, id invite.InviteID) (*invite.Invite, error)) *InviteFinderByID_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type InviteFinderByID
func (_mock *InviteFinderByID) Save(ctx context.Context, i *invite.Invite) error {
	ret := _mock.Called(ctx, i)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *invite.Invite) error); ok {
		r0 = returnFunc(ctx, i)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InviteFinderByID_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type InviteFinderByID_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - i *invite.Invite
func (_e *InviteFinderByID_Expecter) Save(ctx any, i any) *InviteFinderByID_Save_Call {
	return &InviteFinderByID_Save_Call{Call: _e.mock.On("Save", ctx, i)}
}

func (_c *InviteFinderByID_Save_Call) Run(run func(ctx context.Context, i *invite.Invite)) *InviteFinderByID_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *invite.Invite
		if args[1] != nil {
			arg1 = args[1].(*invite.Invite)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InviteFinderByID_Save_Call) Return(err error) *InviteFinderByID_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InviteFinderByID_Save_Call) RunAndReturn(run func(ctx context.Context, i *invite.Invite) error) *InviteFinderByID_Save_Call {
	_c.Call.Return(run)
	return _c
}
