// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/whicu/hsa/internal/domain/invite"
)

// NewInviteSaver creates a new instance of InviteSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInviteSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *InviteSaver {
	mock := &InviteSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InviteSaver is an autogenerated mock type for the InviteSaver type
type InviteSaver struct {
	mock.Mock
}

type InviteSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *InviteSaver) EXPECT() *InviteSaver_Expecter {
	return &InviteSaver_Expecter{mock: &_m.Mock}
}

// Save provides a mock function for the type InviteSaver
func (_mock *InviteSaver) Save(ctx context.Context, i *invite.Invite) error {
	ret := _mock.Called(ctx, i)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *invite.Invite) error); ok {
		r0 = returnFunc(ctx, i)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InviteSaver_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type InviteSaver_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - i *invite.Invite
func (_e *InviteSaver_Expecter) Save(ctx any, i any) *InviteSaver_Save_Call {
	return &InviteSaver_Save_Call{Call: _e.mock.On("Save", ctx, i)}
}

func (_c *InviteSaver_Save_Call) Run(run func(ctx context.Context, i *invite.Invite)) *InviteSaver_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *invite.Invite
		if args[1] != nil {
			arg1 = args[1].(*invite.Invite)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InviteSaver_Save_Call) Return(err error) *InviteSaver_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InviteSaver_Save_Call) RunAndReturn(run func(ctx context.Context, i *invite.Invite) error) *InviteSaver_Save_Call {
	_c.Call.Return(run)
	return _c
}
