// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/whicu/hsa/internal/domain/invite"
)

// NewInviteFinderByCode creates a new instance of InviteFinderByCode. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInviteFinderByCode(t interface {
	mock.TestingT
	Cleanup(func())
}) *InviteFinderByCode {
	mock := &InviteFinderByCode{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InviteFinderByCode is an autogenerated mock type for the InviteFinderByCode type
type InviteFinderByCode struct {
	mock.Mock
}

type InviteFinderByCode_Expecter struct {
	mock *mock.Mock
}

func (_m *InviteFinderByCode) EXPECT() *InviteFinderByCode_Expecter {
	return &InviteFinderByCode_Expecter{mock: &_m.Mock}
}

// FindByCodeHash provides a mock function for the type InviteFinderByCode
func (_mock *InviteFinderByCode) FindByCodeHash(ctx context.Context, hash string) (*invite.Invite, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for FindByCodeHash")
	}

	var r0 *invite.Invite
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*invite.Invite, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *invite.Invite); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*invite.Invite)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InviteFinderByCode_FindByCodeHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCodeHash'
type InviteFinderByCode_FindByCodeHash_Call struct {
	*mock.Call
}

// FindByCodeHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *InviteFinderByCode_Expecter) FindByCodeHash(ctx any, hash any) *InviteFinderByCode_FindByCodeHash_Call {
	return &InviteFinderByCode_FindByCodeHash_Call{Call: _e.mock.On("FindByCodeHash", ctx, hash)}
}

func (_c *InviteFinderByCode_FindByCodeHash_Call) Run(run func(ctx context.Context, hash string)) *InviteFinderByCode_FindByCodeHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InviteFinderByCode_FindByCodeHash_Call) Return(invite1 *invite.Invite, err error) *InviteFinderByCode_FindByCodeHash_Call {
	_c.Call.Return(invite1, err)
	return _c
}

func (_c *InviteFinderByCode_FindByCodeHash_Call) RunAndReturn(run func(ctx context.Context, hash string) (*invite.Invite, error)) *InviteFinderByCode_FindByCodeHash_Call {
	_c.Call.Return(run)
	return _c
}
