// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/whicu/hsa/internal/domain/session"
)

// NewRefreshTokenFinder creates a new instance of RefreshTokenFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshTokenFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshTokenFinder {
	mock := &RefreshTokenFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RefreshTokenFinder is an autogenerated mock type for the RefreshTokenFinder type
type RefreshTokenFinder struct {
	mock.Mock
}

type RefreshTokenFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *RefreshTokenFinder) EXPECT() *RefreshTokenFinder_Expecter {
	return &RefreshTokenFinder_Expecter{mock: &_m.Mock}
}

// FindByTokenHash provides a mock function for the type RefreshTokenFinder
func (_mock *RefreshTokenFinder) FindByTokenHash(ctx context.Context, hash string) (*session.RefreshToken, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for FindByTokenHash")
	}

	var r0 *session.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*session.RefreshToken, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *session.RefreshToken); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*session.RefreshToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RefreshTokenFinder_FindByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTokenHash'
type RefreshTokenFinder_FindByTokenHash_Call struct {
	*mock.Call
}

// FindByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *RefreshTokenFinder_Expecter) FindByTokenHash(ctx any, hash any) *RefreshTokenFinder_FindByTokenHash_Call {
	return &RefreshTokenFinder_FindByTokenHash_Call{Call: _e.mock.On("FindByTokenHash", ctx, hash)}
}

func (_c *RefreshTokenFinder_FindByTokenHash_Call) Run(run func(ctx context.Context, hash string)) *RefreshTokenFinder_FindByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RefreshTokenFinder_FindByTokenHash_Call) Return(refreshToken *session.RefreshToken, err error) *RefreshTokenFinder_FindByTokenHash_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *RefreshTokenFinder_FindByTokenHash_Call) RunAndReturn(run func(ctx context.Context, hash string) (*session.RefreshToken, error)) *RefreshTokenFinder_FindByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}
