// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/whicu/hsa/internal/domain/session"
)

// NewRefreshTokenFinderByID creates a new instance of RefreshTokenFinderByID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshTokenFinderByID(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshTokenFinderByID {
	mock := &RefreshTokenFinderByID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RefreshTokenFinderByID is an autogenerated mock type for the RefreshTokenFinderByID type
type RefreshTokenFinderByID struct {
	mock.Mock
}

type RefreshTokenFinderByID_Expecter struct {
	mock *mock.Mock
}

func (_m *RefreshTokenFinderByID) EXPECT() *RefreshTokenFinderByID_Expecter {
	return &RefreshTokenFinderByID_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type RefreshTokenFinderByID
func (_mock *RefreshTokenFinderByID) FindByID(ctx context.Context, id session.RefreshTokenID) (*session.RefreshToken, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *session.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, session.RefreshTokenID) (*session.RefreshToken, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, session.RefreshTokenID) *session.RefreshToken); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*session.RefreshToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, session.RefreshTokenID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RefreshTokenFinderByID_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type RefreshTokenFinderByID_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id session.RefreshTokenID
func (_e *RefreshTokenFinderByID_Expecter) FindByID(ctx any, id any) *RefreshTokenFinderByID_FindByID_Call {
	return &RefreshTokenFinderByID_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *RefreshTokenFinderByID_FindByID_Call) Run(run func(ctx context.Context, id session.RefreshTokenID)) *RefreshTokenFinderByID_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 session.RefreshTokenID
		if args[1] != nil {
			arg1 = args[1].(session.RefreshTokenID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RefreshTokenFinderByID_FindByID_Call) Return(refreshToken *session.RefreshToken, err error) *RefreshTokenFinderByID_FindByID_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *RefreshTokenFinderByID_FindByID_Call) RunAndReturn(run func(ctx context.Context, id session.RefreshTokenID) (*session.RefreshToken, error)) *RefreshTokenFinderByID_FindByID_Call {
	_c.Call.Return(run)
	return _c
}
