// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/whicu/hsa/internal/domain/session"
)

// NewRefreshTokenBatchSaver creates a new instance of RefreshTokenBatchSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshTokenBatchSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshTokenBatchSaver {
	mock := &RefreshTokenBatchSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RefreshTokenBatchSaver is an autogenerated mock type for the RefreshTokenBatchSaver type
type RefreshTokenBatchSaver struct {
	mock.Mock
}

type RefreshTokenBatchSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *RefreshTokenBatchSaver) EXPECT() *RefreshTokenBatchSaver_Expecter {
	return &RefreshTokenBatchSaver_Expecter{mock: &_m.Mock}
}

// SaveAll provides a mock function for the type RefreshTokenBatchSaver
func (_mock *RefreshTokenBatchSaver) SaveAll(ctx context.Context, tokens []*session.RefreshToken) error {
	ret := _mock.Called(ctx, tokens)

	if len(ret) == 0 {
		panic("no return value specified for SaveAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*session.RefreshToken) error); ok {
		r0 = returnFunc(ctx, tokens)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RefreshTokenBatchSaver_SaveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAll'
type RefreshTokenBatchSaver_SaveAll_Call struct {
	*mock.Call
}

// SaveAll is a helper method to define mock.On call
//   - ctx context.Context
//   - tokens []*session.RefreshToken
func (_e *RefreshTokenBatchSaver_Expecter) SaveAll(ctx any, tokens any) *RefreshTokenBatchSaver_SaveAll_Call {
	return &RefreshTokenBatchSaver_SaveAll_Call{Call: _e.mock.On("SaveAll", ctx, tokens)}
}

func (_c *RefreshTokenBatchSaver_SaveAll_Call) Run(run func(ctx context.Context, tokens []*session.RefreshToken)) *RefreshTokenBatchSaver_SaveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*session.RefreshToken
		if args[1] != nil {
			arg1 = args[1].([]*session.RefreshToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RefreshTokenBatchSaver_SaveAll_Call) Return(err error) *RefreshTokenBatchSaver_SaveAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RefreshTokenBatchSaver_SaveAll_Call) RunAndReturn(run func(ctx context.Context, tokens []*session.RefreshToken) error) *RefreshTokenBatchSaver_SaveAll_Call {
	_c.Call.Return(run)
	return _c
}
