// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/whicu/hsa/internal/application"
	"github.com/whicu/hsa/internal/domain/invite"
	"github.com/whicu/hsa/internal/domain/user"
)

// NewRegistrator creates a new instance of Registrator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegistrator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Registrator {
	mock := &Registrator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Registrator is an autogenerated mock type for the Registrator type
type Registrator struct {
	mock.Mock
}

type Registrator_Expecter struct {
	mock *mock.Mock
}

func (_m *Registrator) EXPECT() *Registrator_Expecter {
	return &Registrator_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function for the type Registrator
func (_mock *Registrator) Begin(ctx context.Context, candidateUserID user.UserID, inviteID invite.InviteID) (string, []byte, error) {
	ret := _mock.Called(ctx, candidateUserID, inviteID)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 string
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.UserID, invite.InviteID) (string, []byte, error)); ok {
		return returnFunc(ctx, candidateUserID, inviteID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.UserID, invite.InviteID) string); ok {
		r0 = returnFunc(ctx, candidateUserID, inviteID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.UserID, invite.InviteID) []byte); ok {
		r1 = returnFunc(ctx, candidateUserID, inviteID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, user.UserID, invite.InviteID) error); ok {
		r2 = returnFunc(ctx, candidateUserID, inviteID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Registrator_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type Registrator_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
//   - candidateUserID user.UserID
//   - inviteID invite.InviteID
func (_e *Registrator_Expecter) Begin(ctx any, candidateUserID any, inviteID any) *Registrator_Begin_Call {
	return &Registrator_Begin_Call{Call: _e.mock.On("Begin", ctx, candidateUserID, inviteID)}
}

func (_c *Registrator_Begin_Call) Run(run func(ctx context.Context, candidateUserID user.UserID, inviteID invite.InviteID)) *Registrator_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.UserID
		if args[1] != nil {
			arg1 = args[1].(user.UserID)
		}
		var arg2 invite.InviteID
		if args[2] != nil {
			arg2 = args[2].(invite.InviteID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Registrator_Begin_Call) Return(challengeToken string, creationOptions []byte, err error) *Registrator_Begin_Call {
	_c.Call.Return(challengeToken, creationOptions, err)
	return _c
}

func (_c *Registrator_Begin_Call) RunAndReturn(run func(ctx context.Context, candidateUserID user.UserID, inviteID invite.InviteID) (string, []byte, error)) *Registrator_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Finish provides a mock function for the type Registrator
func (_mock *Registrator) Finish(ctx context.Context, challengeToken string, response []byte) (application.RegistrationResult, error) {
	ret := _mock.Called(ctx, challengeToken, response)

	if len(ret) == 0 {
		panic("no return value specified for Finish")
	}

	var r0 application.RegistrationResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) (application.RegistrationResult, error)); ok {
		return returnFunc(ctx, challengeToken, response)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) application.RegistrationResult); ok {
		r0 = returnFunc(ctx, challengeToken, response)
	} else {
		r0 = ret.Get(0).(application.RegistrationResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = returnFunc(ctx, challengeToken, response)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Registrator_Finish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Finish'
type Registrator_Finish_Call struct {
	*mock.Call
}

// Finish is a helper method to define mock.On call
//   - ctx context.Context
//   - challengeToken string
//   - response []byte
func (_e *Registrator_Expecter) Finish(ctx any, challengeToken any, response any) *Registrator_Finish_Call {
	return &Registrator_Finish_Call{Call: _e.mock.On("Finish", ctx, challengeToken, response)}
}

func (_c *Registrator_Finish_Call) Run(run func(ctx context.Context, challengeToken string, response []byte)) *Registrator_Finish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Registrator_Finish_Call) Return(registrationResult application.RegistrationResult, err error) *Registrator_Finish_Call {
	_c.Call.Return(registrationResult, err)
	return _c
}

func (_c *Registrator_Finish_Call) RunAndReturn(run func(ctx context.Context, challengeToken string, response []byte) (application.RegistrationResult, error)) *Registrator_Finish_Call {
	_c.Call.Return(run)
	return _c
}
