// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/whicu/hsa/internal/domain/user"
)

// NewRootFinder creates a new instance of RootFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRootFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *RootFinder {
	mock := &RootFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RootFinder is an autogenerated mock type for the RootFinder type
type RootFinder struct {
	mock.Mock
}

type RootFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *RootFinder) EXPECT() *RootFinder_Expecter {
	return &RootFinder_Expecter{mock: &_m.Mock}
}

// FindRoot provides a mock function for the type RootFinder
func (_mock *RootFinder) FindRoot(ctx context.Context) (*user.User, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindRoot")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*user.User, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *user.User); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RootFinder_FindRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRoot'
type RootFinder_FindRoot_Call struct {
	*mock.Call
}

// FindRoot is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RootFinder_Expecter) FindRoot(ctx any) *RootFinder_FindRoot_Call {
	return &RootFinder_FindRoot_Call{Call: _e.mock.On("FindRoot", ctx)}
}

func (_c *RootFinder_FindRoot_Call) Run(run func(ctx context.Context)) *RootFinder_FindRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RootFinder_FindRoot_Call) Return(user1 *user.User, err error) *RootFinder_FindRoot_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *RootFinder_FindRoot_Call) RunAndReturn(run func(ctx context.Context) (*user.User, error)) *RootFinder_FindRoot_Call {
	_c.Call.Return(run)
	return _c
}
