// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/whicu/hsa/internal/domain/user"
)

// NewTokenIssuer creates a new instance of TokenIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenIssuer {
	mock := &TokenIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenIssuer is an autogenerated mock type for the TokenIssuer type
type TokenIssuer struct {
	mock.Mock
}

type TokenIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenIssuer) EXPECT() *TokenIssuer_Expecter {
	return &TokenIssuer_Expecter{mock: &_m.Mock}
}

// IssueAccessToken provides a mock function for the type TokenIssuer
func (_mock *TokenIssuer) IssueAccessToken(userID user.UserID, ttl time.Duration) (string, error) {
	ret := _mock.Called(userID, ttl)

	if len(ret) == 0 {
		panic("no return value specified for IssueAccessToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(user.UserID, time.Duration) (string, error)); ok {
		return returnFunc(userID, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(user.UserID, time.Duration) string); ok {
		r0 = returnFunc(userID, ttl)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(user.UserID, time.Duration) error); ok {
		r1 = returnFunc(userID, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenIssuer_IssueAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueAccessToken'
type TokenIssuer_IssueAccessToken_Call struct {
	*mock.Call
}

// IssueAccessToken is a helper method to define mock.On call
//   - userID user.UserID
//   - ttl time.Duration
func (_e *TokenIssuer_Expecter) IssueAccessToken(userID any, ttl any) *TokenIssuer_IssueAccessToken_Call {
	return &TokenIssuer_IssueAccessToken_Call{Call: _e.mock.On("IssueAccessToken", userID, ttl)}
}

func (_c *TokenIssuer_IssueAccessToken_Call) Run(run func(userID user.UserID, ttl time.Duration)) *TokenIssuer_IssueAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 user.UserID
		if args[0] != nil {
			arg0 = args[0].(user.UserID)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenIssuer_IssueAccessToken_Call) Return(s string, err error) *TokenIssuer_IssueAccessToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *TokenIssuer_IssueAccessToken_Call) RunAndReturn(run func(userID user.UserID, ttl time.Duration) (string, error)) *TokenIssuer_IssueAccessToken_Call {
	_c.Call.Return(run)
	return _c
}
