// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewTokenGenerator creates a new instance of TokenGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenGenerator {
	mock := &TokenGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenGenerator is an autogenerated mock type for the TokenGenerator type
type TokenGenerator struct {
	mock.Mock
}

type TokenGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenGenerator) EXPECT() *TokenGenerator_Expecter {
	return &TokenGenerator_Expecter{mock: &_m.Mock}
}

// GenerateToken provides a mock function for the type TokenGenerator
func (_mock *TokenGenerator) GenerateToken(length int) (string, string, error) {
	ret := _mock.Called(length)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(int) (string, string, error)); ok {
		return returnFunc(length)
	}
	if returnFunc, ok := ret.Get(0).(func(int) string); ok {
		r0 = returnFunc(length)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(int) string); ok {
		r1 = returnFunc(length)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(int) error); ok {
		r2 = returnFunc(length)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// TokenGenerator_GenerateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateToken'
type TokenGenerator_GenerateToken_Call struct {
	*mock.Call
}

// GenerateToken is a helper method to define mock.On call
//   - length int
func (_e *TokenGenerator_Expecter) GenerateToken(length any) *TokenGenerator_GenerateToken_Call {
	return &TokenGenerator_GenerateToken_Call{Call: _e.mock.On("GenerateToken", length)}
}

func (_c *TokenGenerator_GenerateToken_Call) Run(run func(length int)) *TokenGenerator_GenerateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TokenGenerator_GenerateToken_Call) Return(token string, hash string, err error) *TokenGenerator_GenerateToken_Call {
	_c.Call.Return(token, hash, err)
	return _c
}

func (_c *TokenGenerator_GenerateToken_Call) RunAndReturn(run func(length int) (string, string, error)) *TokenGenerator_GenerateToken_Call {
	_c.Call.Return(run)
	return _c
}
