// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/whicu/hsa/internal/domain/user"
)

// NewUserFinderByID creates a new instance of UserFinderByID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserFinderByID(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserFinderByID {
	mock := &UserFinderByID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserFinderByID is an autogenerated mock type for the UserFinderByID type
type UserFinderByID struct {
	mock.Mock
}

type UserFinderByID_Expecter struct {
	mock *mock.Mock
}

func (_m *UserFinderByID) EXPECT() *UserFinderByID_Expecter {
	return &UserFinderByID_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type UserFinderByID
func (_mock *UserFinderByID) FindByID(ctx context.Context, id user.UserID) (*user.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.UserID) (*user.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.UserID) *user.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.UserID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserFinderByID_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type UserFinderByID_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id user.UserID
func (_e *UserFinderByID_Expecter) FindByID(ctx any, id any) *UserFinderByID_FindByID_Call {
	return &UserFinderByID_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *UserFinderByID_FindByID_Call) Run(run func(ctx context.Context, id user.UserID)) *UserFinderByID_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.UserID
		if args[1] != nil {
			arg1 = args[1].(user.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserFinderByID_FindByID_Call) Return(user1 *user.User, err error) *UserFinderByID_FindByID_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *UserFinderByID_FindByID_Call) RunAndReturn(run func(ctx context.Context, id user.UserID) (*user.User, error)) *UserFinderByID_FindByID_Call {
	_c.Call.Return(run)
	return _c
}
