// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/whicu/hsa/internal/domain/user"
)

// NewUserDescendantsFinder creates a new instance of UserDescendantsFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserDescendantsFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserDescendantsFinder {
	mock := &UserDescendantsFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserDescendantsFinder is an autogenerated mock type for the UserDescendantsFinder type
type UserDescendantsFinder struct {
	mock.Mock
}

type UserDescendantsFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *UserDescendantsFinder) EXPECT() *UserDescendantsFinder_Expecter {
	return &UserDescendantsFinder_Expecter{mock: &_m.Mock}
}

// Descendants provides a mock function for the type UserDescendantsFinder
func (_mock *UserDescendantsFinder) Descendants(ctx context.Context, root user.UserID) ([]user.UserID, error) {
	ret := _mock.Called(ctx, root)

	if len(ret) == 0 {
		panic("no return value specified for Descendants")
	}

	var r0 []user.UserID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.UserID) ([]user.UserID, error)); ok {
		return returnFunc(ctx, root)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.UserID) []user.UserID); ok {
		r0 = returnFunc(ctx, root)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.UserID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.UserID) error); ok {
		r1 = returnFunc(ctx, root)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserDescendantsFinder_Descendants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Descendants'
type UserDescendantsFinder_Descendants_Call struct {
	*mock.Call
}

// Descendants is a helper method to define mock.On call
//   - ctx context.Context
//   - root user.UserID
func (_e *UserDescendantsFinder_Expecter) Descendants(ctx any, root any) *UserDescendantsFinder_Descendants_Call {
	return &UserDescendantsFinder_Descendants_Call{Call: _e.mock.On("Descendants", ctx, root)}
}

func (_c *UserDescendantsFinder_Descendants_Call) Run(run func(ctx context.Context, root user.UserID)) *UserDescendantsFinder_Descendants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.UserID
		if args[1] != nil {
			arg1 = args[1].(user.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserDescendantsFinder_Descendants_Call) Return(userIDs []user.UserID, err error) *UserDescendantsFinder_Descendants_Call {
	_c.Call.Return(userIDs, err)
	return _c
}

func (_c *UserDescendantsFinder_Descendants_Call) RunAndReturn(run func(ctx context.Context, root user.UserID) ([]user.UserID, error)) *UserDescendantsFinder_Descendants_Call {
	_c.Call.Return(run)
	return _c
}
