// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/whicu/hsa/internal/domain/user"
)

// NewUserSaver creates a new instance of UserSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserSaver {
	mock := &UserSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserSaver is an autogenerated mock type for the UserSaver type
type UserSaver struct {
	mock.Mock
}

type UserSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *UserSaver) EXPECT() *UserSaver_Expecter {
	return &UserSaver_Expecter{mock: &_m.Mock}
}

// Save provides a mock function for the type UserSaver
func (_mock *UserSaver) Save(ctx context.Context, u *user.User) error {
	ret := _mock.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.User) error); ok {
		r0 = returnFunc(ctx, u)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserSaver_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type UserSaver_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - u *user.User
func (_e *UserSaver_Expecter) Save(ctx any, u any) *UserSaver_Save_Call {
	return &UserSaver_Save_Call{Call: _e.mock.On("Save", ctx, u)}
}

func (_c *UserSaver_Save_Call) Run(run func(ctx context.Context, u *user.User)) *UserSaver_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *user.User
		if args[1] != nil {
			arg1 = args[1].(*user.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserSaver_Save_Call) Return(err error) *UserSaver_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserSaver_Save_Call) RunAndReturn(run func(ctx context.Context, u *user.User) error) *UserSaver_Save_Call {
	_c.Call.Return(run)
	return _c
}
