// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/whicu/hsa/internal/domain/key"
)

// NewWrappedKeySaver creates a new instance of WrappedKeySaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWrappedKeySaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *WrappedKeySaver {
	mock := &WrappedKeySaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WrappedKeySaver is an autogenerated mock type for the WrappedKeySaver type
type WrappedKeySaver struct {
	mock.Mock
}

type WrappedKeySaver_Expecter struct {
	mock *mock.Mock
}

func (_m *WrappedKeySaver) EXPECT() *WrappedKeySaver_Expecter {
	return &WrappedKeySaver_Expecter{mock: &_m.Mock}
}

// SaveAll provides a mock function for the type WrappedKeySaver
func (_mock *WrappedKeySaver) SaveAll(ctx context.Context, keys []*key.WrappedKey) error {
	ret := _mock.Called(ctx, keys)

	if len(ret) == 0 {
		panic("no return value specified for SaveAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*key.WrappedKey) error); ok {
		r0 = returnFunc(ctx, keys)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WrappedKeySaver_SaveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAll'
type WrappedKeySaver_SaveAll_Call struct {
	*mock.Call
}

// SaveAll is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []*key.WrappedKey
func (_e *WrappedKeySaver_Expecter) SaveAll(ctx any, keys any) *WrappedKeySaver_SaveAll_Call {
	return &WrappedKeySaver_SaveAll_Call{Call: _e.mock.On("SaveAll", ctx, keys)}
}

func (_c *WrappedKeySaver_SaveAll_Call) Run(run func(ctx context.Context, keys []*key.WrappedKey)) *WrappedKeySaver_SaveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*key.WrappedKey
		if args[1] != nil {
			arg1 = args[1].([]*key.WrappedKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WrappedKeySaver_SaveAll_Call) Return(err error) *WrappedKeySaver_SaveAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WrappedKeySaver_SaveAll_Call) RunAndReturn(run func(ctx context.Context, keys []*key.WrappedKey) error) *WrappedKeySaver_SaveAll_Call {
	_c.Call.Return(run)
	return _c
}
